# Pandas

In [1]:
import pandas as pd

# from dict
df = pd.DataFrame({
    'name'    : ['Ashish', 'Prince', 'Bob', 'Alice'],
    'age'     : [20, 22, 21, 23],
    'marks'   : [85, 90, 75, 88],
    'city'    : ['Delhi', 'Mumbai', 'Pune', 'Chennai']
})

print(df)

     name  age  marks     city
0  Ashish   20     85    Delhi
1  Prince   22     90   Mumbai
2     Bob   21     75     Pune
3   Alice   23     88  Chennai

In [2]:
# from list of dicts
data = [
    {'name': 'Ashish', 'marks': 85},
    {'name': 'Prince', 'marks': 90},
]
df = pd.DataFrame(data)
print(df)

     name  marks
0  Ashish     85
1  Prince     90

In [3]:
# from list of lists
data = [['Ashish', 85], ['Prince', 90]]
df   = pd.DataFrame(data, columns=['name', 'marks'])
print(df)

     name  marks
0  Ashish     85
1  Prince     90

## Series with python Functionality

In [4]:
data=pd.read_csv('youtube_2025_dataset_202504061614.csv')

In [5]:
type(data)

pandas.DataFrame

In [6]:
len(data)

5000

In [7]:
data.shape

(5000, 14)

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Channel Name                 5000 non-null   str
 1   Youtuber Name                5000 non-null   str
 2   Total Videos                 5000 non-null   int64
 3   Best Video                   5000 non-null   str
 4   Avg Video Length (min)       5000 non-null   float64
 5   Total Subscribers            5000 non-null   int64
 6   Members Count                5000 non-null   int64
 7   AI Generated Content (%)     5000 non-null   int64
 8   Neural Interface Compatible  5000 non-null   bool
 9   Metaverse Integration Level  3718 non-null   str
 10  Quantum Computing Topics     5000 non-null   int64
 11  Holographic Content Rating   5000 non-null   str
 12  Engagement Score             5000 non-null   float64
 13  Content Value Index          5000 non-null   float64
dtypes: bool(1), float64(3), int64(5), str(5)
memory usage: 872.9 KB

In [9]:
data.head()

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
0,Smith-Ross Labs,Eric Patel,68,VR Challenge: Review 2023,24.8,8264152,303319,9,True,Full,5,3D,130655.44,6.2
1,Sandoval PLC Hub,Cynthia Harrington,128,Nanotech Simulation: Analysis 2024,22.9,8768222,384629,62,False,NaN,4,3D,138624.73,21.4
2,"Jones, Moore and Ho Network",Amanda Walker,282,Metaverse Interface: Analysis 2024,24.0,6163386,361743,31,True,Advanced,6,1D,97442.53,13.5
3,Mitchell-Hooper Labs,Jessica Nelson MD,302,VR Protocol: Review 2023,24.6,4712268,58483,5,False,NaN,15,1D,74500.50,12.0
4,Wilson LLC Studios,Matthew Sherman,129,Nanotech Simulation: Review 2024,24.6,9592017,333873,63,True,NaN,12,3D,151648.85,27.3

In [10]:
data.sort_values('Total Videos',ascending=False).head(5)

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Neural Interface Compatible,Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
232,"Davis, Calderon and Morgan Labs",Paul Silva,500,VR Protocol: Tutorial 2025,23.6,2808201,53407,82,True,Advanced,0,2D,44397.38,24.6
492,"Suarez, Martinez and Miller Network",Amy Russo,500,VR Unboxing: Analysis 2025,24.0,342315,451860,57,True,Advanced,16,4D,5411.97,28.3
1946,Jones Group Hub,Miguel Ross,500,Nanotech Interface: Showcase 2024,23.6,5543313,279134,71,True,Advanced,19,1D,87639.24,34.6
392,"Morris, Howard and Reed Hub",William Jones,500,Nanotech Challenge: Breakdown 2025,23.6,8668667,282123,92,True,Advanced,0,2D,137050.78,27.6
1102,"Dixon, Robles and Holt Labs",Philip Adkins,500,Metaverse Unboxing: Experience 2024,23.5,1365186,241572,8,True,Basic,14,2D,21583.46,12.2

In [16]:
new_data=data.groupby('Neural Interface Compatible')
new_data.count()

,Channel Name,Youtuber Name,Total Videos,Best Video,Avg Video Length (min),Total Subscribers,Members Count,AI Generated Content (%),Metaverse Integration Level,Quantum Computing Topics,Holographic Content Rating,Engagement Score,Content Value Index
Neural Interface Compatible,,,,,,,,,,,,,
False,2471,2471,2471,2471,2471,2471,2471,2471,1817,2471,2471,2471,2471
True,2529,2529,2529,2529,2529,2529,2529,2529,1901,2529,2529,2529,2529