#  1. CSV files

### can be downloaded from kaggle

# 2. Database

# 3. Json

# 4. Excel

# 5. API (Application Programming Interface)

# 6. Web Scrapping

In [1]:
import pandas as pd

In [2]:
# Data Gathering from read_csv

dg1=pd.read_csv('data/Student Depression Dataset.csv')

In [3]:
dg1.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0

In [4]:
# Data Gathering from excel file
dg2=pd.read_excel('data/01 Retail Inventory.xlsx')

In [5]:
dg2.head()

,Product ID,Product Name,Category,Supplier Name,Unit Cost,Retail Price,Opening Stock,Units Sold,Closing Stock,Reorder Point,Stock Status
0,PRD-1001,Wine Glasses,Home & Kitchen,Heritage Brands,23.78,38.89,135,118,17,30,Low Stock
1,PRD-1002,Eye Mask,Beauty,Coastal Trading,15.67,24.53,86,10,76,9,In Stock
2,PRD-1003,Resistance Band,Sports & Outdoors,National Supply Group,5.59,11.88,319,195,124,47,In Stock
3,PRD-1004,Action Figure,Toys & Games,Pacific Wholesale,9.72,18.01,173,140,33,39,Low Stock
4,PRD-1005,Serving Tray,Home & Kitchen,Coastal Trading,8.22,13.90,32,8,24,7,In Stock

In [6]:
# reading tsv file
#tsv stands for ---> Tab Space Value

In [7]:
dg3=pd.read_csv('data/demo_mlexpec.tsv',sep='\t')

In [8]:
dg3

,"unit,sex,age,geo\time",2021,2020,2019,2018,2017,2016,2015,2014,2013,...,1969,1968,1967,1966,1965,1964,1963,1962,1961,1960
0,"YR,F,Y1,AL",:,79.4,80.4,80.2,79.7,79.8,79.2,79.8,79.6,...,:,:,:,:,:,:,:,:,:,:
1,"YR,F,Y1,AM",:,:,79.1,79.2,78.5,78.0,77.9,:,:,...,:,:,:,:,:,:,:,:,:,:
2,"YR,F,Y1,AT",:,82.9,83.5,83.3,83.2,83.4,83.0,83.3,83.0,...,:,:,:,:,:,:,:,:,:,:
3,"YR,F,Y1,AZ",:,:,78.6,78.1,77.7,:,77.5,77.0,76.9,...,:,:,:,:,:,:,:,:,:,:
4,"YR,F,Y1,BE",:,82.3,83.6,83.2,83.2,83.2,82.6,83.1,82.5,...,74.4,74.3,74.7,74.4,74.3,74.6,73.9,74.0,74.5,73.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14443,"YR,T,Y_LT1,SM",:,:,:,:,:,:,:,:,:,...,:,:,:,:,:,:,:,:,:,:
14444,"YR,T,Y_LT1,TR",:,:,79.1,78.9,78.5,78.1,78.2,78.1,78.2,...,:,:,:,:,:,:,:,:,:,:
14445,"YR,T,Y_LT1,UA",:,:,73.4,73.2,73.3,72.9,72.5,71.8,:,...,:,:,:,:,:,:,:,:,:,:
14446,"YR,T,Y_LT1,UK",:,:,:,81.3,81.3,81.2,81.0,81.4,81.1,...,:,:,:,:,:,:,:,:,:,:
14447,"YR,T,Y_LT1,XK",:,:,:,:,:,78.6 p,:,:,:,...,:,:,:,:,:,:,:,:,:,:

#### names ----> names is going to take a list of names that we can provide to our column names only

In [9]:
data_path='/Users/ashishsingh/Desktop/GEN AI/08. Machine Learning/data/Student Depression Dataset.csv'
dg4=pd.read_csv(data_path,names=[ 'student_id',	'Gender',	'Age',	'City',	'Profession',	'Academic Pressure',	'Work Pressure',	'CGPA',	'Study Satisfaction',	'Job Satisfaction', 'Sleep Duration',	'Dietary Habits',	'Degree',	'suicidal thoughts', 	'Work/Study Hours',	'Financial Stress',	'Mental Illness',	'Depression'])

In [10]:
dg4.head()

,student_id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,suicidal thoughts,Work/Study Hours,Financial Stress,Mental Illness,Depression
0,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
1,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
2,8,Female,24.0,Bangalore,Student,2.0,0.0,5.9,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
3,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
4,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1

In [11]:
dg5=pd.read_csv(data_path)

In [12]:
dg5.info()

<class 'pandas.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  str
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  str
 4   Profession                             27901 non-null  str
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  str
 11  Dietary Habits                         27901 non-null  str
 12  Degree                                 27901 non-null  str
 13  Have you ever had suicidal thoughts ?  27901 non-null  str
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27898 non-null  float64
 16  Family History of Mental Illness       27901 non-null  str
 17  Depression                             27901 non-null  int64
dtypes: float64(8), int64(2), str(8)
memory usage: 5.2 MB

In [13]:
dg5['Financial Stress'].unique()

array([ 1.,  2.,  5.,  3.,  4., nan])

In [14]:
median_value=dg5['Financial Stress'].median()
dg5['Financial Stress'].fillna(median_value)

0        1.0
1        2.0
2        1.0
3        5.0
4        1.0
        ...
27896    1.0
27897    3.0
27898    2.0
27899    5.0
27900    3.0
Name: Financial Stress, Length: 27901, dtype: float64

In [15]:
dg5.shape

(27901, 18)

In [16]:
dfs=pd.read_csv(data_path,chunksize=5000)

In [17]:
for chunk in dfs:
    print(chunk.shape)

(5000, 18)
(5000, 18)
(5000, 18)
(5000, 18)
(5000, 18)
(2901, 18)

# Data Gathering in JSON, SQL & Role in Agentic AI and GEN AI Development

### 1. JSON

In [18]:
# DAtA PATH
CSV_DATA='data/Student Depression Dataset.csv'
JSON_DATA='data/iris.json'
TSV_DATA='data/demo_mlexpec.tsv'
EXCEL_DATA='data/01 Retail Inventory.xlsx'

In [19]:
json_data=pd.read_json(JSON_DATA)

In [20]:
json_data.head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

### 2. SQL DATABASE

In [21]:
pip install mysql.connector

Requirement already satisfied: mysql.connector in /Users/ashishsingh/Desktop/GEN AI/.venv/lib/python3.12/site-packages (2.2.9)
Note: you may need to restart the kernel to use updated packages.

In [22]:
import mysql.connector

In [23]:
import mysql.connector
print(mysql.connector.__version__)

9.7.0

In [24]:
pip install --upgrade mysql-connector-python

Requirement already satisfied: mysql-connector-python in /Users/ashishsingh/Desktop/GEN AI/.venv/lib/python3.12/site-packages (9.7.0)
Note: you may need to restart the kernel to use updated packages.

In [25]:
host='localhost'
useer='root'
password='*******'
db='UBER_DATASET'
data=mysql.connector.connect(
    host=host,
    user=useer,
    password=password,
    database=db)

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

In [ ]:
data

In [ ]:
df = pd.read_sql_query('Select * from drivers',data)

/var/folders/c1/6c8s3wn93nd1yg_s50mdh4nc0000gn/T/ipykernel_4035/3727180721.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query('Select * from drivers',data)

In [ ]:
df.head()

,driver_id,user_id,vehicle_make,vehicle_model,vehicle_year,license_plate,rating,join_date,is_active
0,1,1781,Kia,Soul,2015,ZVJ-2140,4.10,2019-12-22,1
1,2,408,Hyundai,Tucson,2016,WLW-3906,4.21,2020-12-14,1
2,3,693,Hyundai,Sonata,2014,WEA-5140,3.81,2023-07-25,1
3,4,187,Nissan,Rogue,2021,KDE-9978,4.82,2020-01-11,1
4,5,1499,Ford,Fusion,2019,EKJ-8600,3.30,2023-07-15,0

In [ ]:
df.shape

(400, 9)

In [ ]:
pd.read_sql_query("select * from payments",data)

/var/folders/c1/6c8s3wn93nd1yg_s50mdh4nc0000gn/T/ipykernel_4035/1866268105.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("select * from payments",data)

       payment_id  trip_id  amount  method   status             paid_at
0               1        1   68.55  wallet  success 2024-06-24 14:24:15
1               2        3    6.36  wallet  success 2023-08-17 09:36:16
2               3        4   21.98    cash  success 2022-11-21 10:17:36
3               4        5   56.99  wallet  success 2022-01-15 14:57:02
4               5        6   55.56    cash  success 2022-05-05 08:34:02
...           ...      ...     ...     ...      ...                 ...
16822       16823    19995   23.30    card  success 2023-02-24 06:37:30
16823       16824    19996   45.59    card   failed 2024-06-05 07:39:25
16824       16825    19997   62.64  wallet  success 2022-04-14 07:53:33
16825       16826    19998   16.77    cash  success 2024-03-28 05:13:13
16826       16827    19999   44.18  wallet  success 2022-06-22 15:12:51

[16827 rows x 6 columns]

In [ ]:
pd.read_sql_query(
    "select * from payments where amount > 100"
    ,data
    )

/var/folders/c1/6c8s3wn93nd1yg_s50mdh4nc0000gn/T/ipykernel_4035/2996508660.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(

     payment_id  trip_id  amount  method   status             paid_at
0            35       41  125.25    cash  success 2023-12-15 20:14:10
1            76       86  118.25    cash  success 2022-08-12 01:36:05
2           103      120  102.71  wallet  success 2024-06-28 20:30:13
3           104      121  121.07    cash  success 2024-01-13 00:47:42
4           137      158  119.41    card  success 2024-03-08 09:02:12
..          ...      ...     ...     ...      ...                 ...
564       16639    19774  102.96  wallet  success 2022-09-19 18:01:01
565       16678    19820  113.21    card  success 2024-01-02 19:17:44
566       16757    19918  106.40  wallet  success 2023-03-13 00:42:17
567       16785    19950  126.76  wallet  success 2023-07-06 18:32:30
568       16804    19975  136.14    card  success 2023-01-13 08:38:52

[569 rows x 6 columns]

In [ ]:
pd.read_sql_query(
    "select * from payments where method='cash'"
    ,data
    )

/var/folders/c1/6c8s3wn93nd1yg_s50mdh4nc0000gn/T/ipykernel_4035/2272188790.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query(

      payment_id  trip_id  amount method   status             paid_at
0              3        4   21.98   cash  success 2022-11-21 10:17:36
1              5        6   55.56   cash  success 2022-05-05 08:34:02
2              6        8    8.70   cash  success 2023-04-17 10:28:36
3              7        9   24.05   cash  success 2022-09-09 23:27:45
4              8       10   38.96   cash  success 2022-06-13 10:41:38
...          ...      ...     ...    ...      ...                 ...
5501       16805    19976   35.14   cash  success 2023-06-12 20:16:22
5502       16811    19982   39.87   cash  success 2022-05-06 05:39:36
5503       16816    19987   34.48   cash  success 2023-01-06 13:18:54
5504       16818    19989    8.80   cash  success 2024-03-17 01:50:03
5505       16826    19998   16.77   cash  success 2024-03-28 05:13:13

[5506 rows x 6 columns]

### 3. API

https://api.themoviedb.org/3/genre/movie/list?api_key=107df16507f64dac79467a3685d428ad&language=en

In [ ]:
url='https://api.themoviedb.org/3/genre/movie/list?language=en'
api_key='107df16507f64dac79467a3685d428ad'

In [ ]:
import requests

In [ ]:
import requests

url = "https://api.themoviedb.org/3/genre/movie/list?api_key=107df16507f64dac79467a3685d428ad&language=en"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxMDdkZjE2NTA3ZjY0ZGFjNzk0NjdhMzY4NWQ0MjhhZCIsIm5iZiI6MTc1ODgwMzE0Mi4zOTIsInN1YiI6IjY4ZDUzNGM2ZmU3ZjYxMWQwZDE5ZGNhMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.XvYrspn1p-9vslUcIZN3DY3FT2uu3m8W1tL9N6inFqQ"
}

response = requests.get(url, headers=headers)

print(response)

<Response [200]>

In [ ]:
response.json()

{'genres': [{'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'},
  {'id': 16, 'name': 'Animation'},
  {'id': 35, 'name': 'Comedy'},
  {'id': 80, 'name': 'Crime'},
  {'id': 99, 'name': 'Documentary'},
  {'id': 18, 'name': 'Drama'},
  {'id': 10751, 'name': 'Family'},
  {'id': 14, 'name': 'Fantasy'},
  {'id': 36, 'name': 'History'},
  {'id': 27, 'name': 'Horror'},
  {'id': 10402, 'name': 'Music'},
  {'id': 9648, 'name': 'Mystery'},
  {'id': 10749, 'name': 'Romance'},
  {'id': 878, 'name': 'Science Fiction'},
  {'id': 10770, 'name': 'TV Movie'},
  {'id': 53, 'name': 'Thriller'},
  {'id': 10752, 'name': 'War'},
  {'id': 37, 'name': 'Western'}]}

In [ ]:
mdb=pd.DataFrame(response.json())

In [ ]:
mdb

                                    genres
0             {'id': 28, 'name': 'Action'}
1          {'id': 12, 'name': 'Adventure'}
2          {'id': 16, 'name': 'Animation'}
3             {'id': 35, 'name': 'Comedy'}
4              {'id': 80, 'name': 'Crime'}
5        {'id': 99, 'name': 'Documentary'}
6              {'id': 18, 'name': 'Drama'}
7          {'id': 10751, 'name': 'Family'}
8            {'id': 14, 'name': 'Fantasy'}
9            {'id': 36, 'name': 'History'}
10            {'id': 27, 'name': 'Horror'}
11          {'id': 10402, 'name': 'Music'}
12         {'id': 9648, 'name': 'Mystery'}
13        {'id': 10749, 'name': 'Romance'}
14  {'id': 878, 'name': 'Science Fiction'}
15       {'id': 10770, 'name': 'TV Movie'}
16          {'id': 53, 'name': 'Thriller'}
17            {'id': 10752, 'name': 'War'}
18           {'id': 37, 'name': 'Western'}

In [ ]:
import requests

url = "https://api.themoviedb.org/3/movie/changes?api_key=107df16507f64dac79467a3685d428ad&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxMDdkZjE2NTA3ZjY0ZGFjNzk0NjdhMzY4NWQ0MjhhZCIsIm5iZiI6MTc1ODgwMzE0Mi4zOTIsInN1YiI6IjY4ZDUzNGM2ZmU3ZjYxMWQwZDE5ZGNhMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.XvYrspn1p-9vslUcIZN3DY3FT2uu3m8W1tL9N6inFqQ"
}

response = requests.get(url, headers=headers)

print(response.text)

{"results":[{"id":4232,"adult":false,"softcore":false},{"id":128128,"adult":false,"softcore":false},{"id":1449851,"adult":true,"softcore":false},{"id":1865,"adult":false,"softcore":false},{"id":1575876,"adult":false,"softcore":false},{"id":1720236,"adult":false,"softcore":false},{"id":1728263,"adult":false,"softcore":false},{"id":1550164,"adult":false,"softcore":false},{"id":1688641,"adult":false,"softcore":false},{"id":1698041,"adult":false,"softcore":false},{"id":1701009,"adult":false,"softcore":false},{"id":1707841,"adult":false,"softcore":false},{"id":1712734,"adult":false,"softcore":false},{"id":1714990,"adult":false,"softcore":false},{"id":1715467,"adult":false,"softcore":false},{"id":1720899,"adult":false,"softcore":false},{"id":1720907,"adult":false,"softcore":false},{"id":1723414,"adult":false,"softcore":false},{"id":1724844,"adult":false,"softcore":false},{"id":1725160,"adult":false,"softcore":false},{"id":1725314,"adult":false,"softcore":false},{"id":1726851,"adult":false,"softcore":false},{"id":1726951,"adult":false,"softcore":false},{"id":1726984,"adult":false,"softcore":false},{"id":1727100,"adult":false,"softcore":false},{"id":1712091,"adult":false,"softcore":false},{"id":1703271,"adult":false,"softcore":false},{"id":1705898,"adult":false,"softcore":false},{"id":1720029,"adult":false,"softcore":false},{"id":1728171,"adult":false,"softcore":false},{"id":1727889,"adult":false,"softcore":false},{"id":1632247,"adult":false,"softcore":false},{"id":1728181,"adult":false,"softcore":false},{"id":1725909,"adult":false,"softcore":false},{"id":1728166,"adult":false,"softcore":false},{"id":1728179,"adult":false,"softcore":false},{"id":1718621,"adult":false,"softcore":false},{"id":1728021,"adult":false,"softcore":false},{"id":1722333,"adult":false,"softcore":false},{"id":1728125,"adult":false,"softcore":false},{"id":1727936,"adult":false,"softcore":false},{"id":1728118,"adult":false,"softcore":false},{"id":1728408,"adult":false,"softcore":false},{"id":1728084,"adult":false,"softcore":false},{"id":187139,"adult":false,"softcore":false},{"id":1193550,"adult":false,"softcore":false},{"id":1507097,"adult":false,"softcore":false},{"id":285,"adult":false,"softcore":false},{"id":58,"adult":false,"softcore":false},{"id":519473,"adult":false,"softcore":false},{"id":467489,"adult":false,"softcore":false},{"id":1659389,"adult":false,"softcore":false},{"id":98545,"adult":false,"softcore":false},{"id":451608,"adult":false,"softcore":false},{"id":1470035,"adult":false,"softcore":false},{"id":1352381,"adult":false,"softcore":false},{"id":1321020,"adult":false,"softcore":false},{"id":1498846,"adult":false,"softcore":false},{"id":433121,"adult":false,"softcore":false},{"id":26748,"adult":false,"softcore":false},{"id":1728411,"adult":false,"softcore":false},{"id":1728412,"adult":false,"softcore":false},{"id":1676178,"adult":true,"softcore":false},{"id":1728413,"adult":false,"softcore":false},{"id":118915,"adult":false,"softcore":false},{"id":1471224,"adult":false,"softcore":false},{"id":567609,"adult":false,"softcore":false},{"id":1295722,"adult":false,"softcore":false},{"id":1727197,"adult":false,"softcore":false},{"id":1728341,"adult":false,"softcore":false},{"id":1728414,"adult":false,"softcore":false},{"id":315162,"adult":false,"softcore":false},{"id":1726808,"adult":null,"softcore":null},{"id":1400336,"adult":false,"softcore":false},{"id":20301,"adult":false,"softcore":false},{"id":1665590,"adult":false,"softcore":false},{"id":1706919,"adult":false,"softcore":false},{"id":1664997,"adult":false,"softcore":false},{"id":1099217,"adult":false,"softcore":false},{"id":1041310,"adult":false,"softcore":false},{"id":50602,"adult":false,"softcore":false},{"id":1728415,"adult":false,"softcore":false},{"id":672647,"adult":false,"softcore":false},{"id":1524040,"adult":false,"softcore":false},{"id":1368337,"adult":false,"softcore":false},{"id":1301401,"adult":false,"softcore":false},{"id":174473,"adult":false,"softcore":false},{"id":1477317,"adult":false,"softcore":false},{"id":1728416,"adult":false,"softcore":false},{"id":1728417,"adult":false,"softcore":false},{"id":10830,"adult":false,"softcore":false},{"id":630072,"adult":true,"softcore":false},{"id":47778,"adult":false,"softcore":false},{"id":12197,"adult":false,"softcore":false},{"id":1563711,"adult":false,"softcore":false},{"id":1189735,"adult":false,"softcore":false},{"id":1728418,"adult":false,"softcore":false},{"id":1728419,"adult":null,"softcore":null},{"id":324857,"adult":false,"softcore":false},{"id":1621607,"adult":false,"softcore":false}],"page":1,"total_pages":37,"total_results":3623}

In [ ]:
mdb=pd.DataFrame(response.json()['results'])
mdb

         id  adult softcore
0      4232  False    False
1    128128  False    False
2   1449851   True    False
3      1865  False    False
4   1575876  False    False
..      ...    ...      ...
95  1189735  False    False
96  1728418  False    False
97  1728419   None     None
98   324857  False    False
99  1621607  False    False

[100 rows x 3 columns]

In [ ]:
import requests

url = "https://api.themoviedb.org/3/account/22336859"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxMDdkZjE2NTA3ZjY0ZGFjNzk0NjdhMzY4NWQ0MjhhZCIsIm5iZiI6MTc1ODgwMzE0Mi4zOTIsInN1YiI6IjY4ZDUzNGM2ZmU3ZjYxMWQwZDE5ZGNhMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.XvYrspn1p-9vslUcIZN3DY3FT2uu3m8W1tL9N6inFqQ"
}

response = requests.get(url, headers=headers)

print(response.text)

{"avatar":{"gravatar":{"hash":"210e81663d9e765704baa42fc5de3cad"},"tmdb":{"avatar_path":null}},"id":22336859,"iso_639_1":"en","iso_3166_1":"IN","name":"","include_adult":false,"username":"ashish_zoro"}

In [ ]:
response.json()

{'avatar': {'gravatar': {'hash': '210e81663d9e765704baa42fc5de3cad'},
  'tmdb': {'avatar_path': None}},
 'id': 22336859,
 'iso_639_1': 'en',
 'iso_3166_1': 'IN',
 'name': '',
 'include_adult': False,
 'username': 'ashish_zoro'}

In [ ]:
pd.DataFrame(response.json())

,avatar,id,iso_639_1,iso_3166_1,name,include_adult,username
gravatar,{'hash': '210e81663d9e765704baa42fc5de3cad'},22336859,en,IN,,False,ashish_zoro
tmdb,{'avatar_path': None},22336859,en,IN,,False,ashish_zoro

In [ ]:
import requests

url = "https://api.themoviedb.org/3/movie/changes?page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxMDdkZjE2NTA3ZjY0ZGFjNzk0NjdhMzY4NWQ0MjhhZCIsIm5iZiI6MTc1ODgwMzE0Mi4zOTIsInN1YiI6IjY4ZDUzNGM2ZmU3ZjYxMWQwZDE5ZGNhMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.XvYrspn1p-9vslUcIZN3DY3FT2uu3m8W1tL9N6inFqQ"
}

response = requests.get(url, headers=headers)

print(response.text)

{"results":[{"id":4232,"adult":false,"softcore":false},{"id":128128,"adult":false,"softcore":false},{"id":1449851,"adult":true,"softcore":false},{"id":1865,"adult":false,"softcore":false},{"id":1575876,"adult":false,"softcore":false},{"id":1720236,"adult":false,"softcore":false},{"id":1728263,"adult":false,"softcore":false},{"id":1550164,"adult":false,"softcore":false},{"id":1688641,"adult":false,"softcore":false},{"id":1698041,"adult":false,"softcore":false},{"id":1701009,"adult":false,"softcore":false},{"id":1707841,"adult":false,"softcore":false},{"id":1712734,"adult":false,"softcore":false},{"id":1714990,"adult":false,"softcore":false},{"id":1715467,"adult":false,"softcore":false},{"id":1720899,"adult":false,"softcore":false},{"id":1720907,"adult":false,"softcore":false},{"id":1723414,"adult":false,"softcore":false},{"id":1724844,"adult":false,"softcore":false},{"id":1725160,"adult":false,"softcore":false},{"id":1725314,"adult":false,"softcore":false},{"id":1726851,"adult":false,"softcore":false},{"id":1726951,"adult":false,"softcore":false},{"id":1726984,"adult":false,"softcore":false},{"id":1727100,"adult":false,"softcore":false},{"id":1712091,"adult":false,"softcore":false},{"id":1703271,"adult":false,"softcore":false},{"id":1705898,"adult":false,"softcore":false},{"id":1720029,"adult":false,"softcore":false},{"id":1728171,"adult":false,"softcore":false},{"id":1727889,"adult":false,"softcore":false},{"id":1632247,"adult":false,"softcore":false},{"id":1728181,"adult":false,"softcore":false},{"id":1725909,"adult":false,"softcore":false},{"id":1728166,"adult":false,"softcore":false},{"id":1728179,"adult":false,"softcore":false},{"id":1718621,"adult":false,"softcore":false},{"id":1728021,"adult":false,"softcore":false},{"id":1722333,"adult":false,"softcore":false},{"id":1728125,"adult":false,"softcore":false},{"id":1727936,"adult":false,"softcore":false},{"id":1728118,"adult":false,"softcore":false},{"id":1728408,"adult":false,"softcore":false},{"id":1728084,"adult":false,"softcore":false},{"id":187139,"adult":false,"softcore":false},{"id":1193550,"adult":false,"softcore":false},{"id":1507097,"adult":false,"softcore":false},{"id":285,"adult":false,"softcore":false},{"id":58,"adult":false,"softcore":false},{"id":519473,"adult":false,"softcore":false},{"id":467489,"adult":false,"softcore":false},{"id":1659389,"adult":false,"softcore":false},{"id":98545,"adult":false,"softcore":false},{"id":451608,"adult":false,"softcore":false},{"id":1470035,"adult":false,"softcore":false},{"id":1352381,"adult":false,"softcore":false},{"id":1321020,"adult":false,"softcore":false},{"id":1498846,"adult":false,"softcore":false},{"id":433121,"adult":false,"softcore":false},{"id":26748,"adult":false,"softcore":false},{"id":1728411,"adult":false,"softcore":false},{"id":1728412,"adult":false,"softcore":false},{"id":1676178,"adult":true,"softcore":false},{"id":1728413,"adult":false,"softcore":false},{"id":118915,"adult":false,"softcore":false},{"id":1471224,"adult":false,"softcore":false},{"id":567609,"adult":false,"softcore":false},{"id":1295722,"adult":false,"softcore":false},{"id":1727197,"adult":false,"softcore":false},{"id":1728341,"adult":false,"softcore":false},{"id":1728414,"adult":false,"softcore":false},{"id":315162,"adult":false,"softcore":false},{"id":1726808,"adult":null,"softcore":null},{"id":1400336,"adult":false,"softcore":false},{"id":20301,"adult":false,"softcore":false},{"id":1665590,"adult":false,"softcore":false},{"id":1706919,"adult":false,"softcore":false},{"id":1664997,"adult":false,"softcore":false},{"id":1099217,"adult":false,"softcore":false},{"id":1041310,"adult":false,"softcore":false},{"id":50602,"adult":false,"softcore":false},{"id":1728415,"adult":false,"softcore":false},{"id":672647,"adult":false,"softcore":false},{"id":1524040,"adult":false,"softcore":false},{"id":1368337,"adult":false,"softcore":false},{"id":1301401,"adult":false,"softcore":false},{"id":174473,"adult":false,"softcore":false},{"id":1477317,"adult":false,"softcore":false},{"id":1728416,"adult":false,"softcore":false},{"id":1728417,"adult":false,"softcore":false},{"id":10830,"adult":false,"softcore":false},{"id":630072,"adult":true,"softcore":false},{"id":47778,"adult":false,"softcore":false},{"id":12197,"adult":false,"softcore":false},{"id":1563711,"adult":false,"softcore":false},{"id":1189735,"adult":false,"softcore":false},{"id":1728418,"adult":false,"softcore":false},{"id":1728419,"adult":null,"softcore":null},{"id":324857,"adult":false,"softcore":false},{"id":1621607,"adult":false,"softcore":false}],"page":1,"total_pages":37,"total_results":3623}

In [ ]:
pd.DataFrame(response.json()['results'])

         id  adult softcore
0      4232  False    False
1    128128  False    False
2   1449851   True    False
3      1865  False    False
4   1575876  False    False
..      ...    ...      ...
95  1189735  False    False
96  1728418  False    False
97  1728419   None     None
98   324857  False    False
99  1621607  False    False

[100 rows x 3 columns]

In [ ]:
import requests

url = "https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&sort_by=popularity.desc"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxMDdkZjE2NTA3ZjY0ZGFjNzk0NjdhMzY4NWQ0MjhhZCIsIm5iZiI6MTc1ODgwMzE0Mi4zOTIsInN1YiI6IjY4ZDUzNGM2ZmU3ZjYxMWQwZDE5ZGNhMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.XvYrspn1p-9vslUcIZN3DY3FT2uu3m8W1tL9N6inFqQ"
}

response = requests.get(url, headers=headers)

print(response.text)

{"page":1,"results":[{"adult":false,"backdrop_path":"/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg","genre_ids":[27,53],"id":1339713,"title":"Obsession","original_language":"en","original_title":"Obsession","overview":"After breaking the mysterious \"One Wish Willow\" to win his crush's heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.","popularity":722.1192,"poster_path":"/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg","release_date":"2026-05-13","softcore":false,"video":false,"vote_average":8.271,"vote_count":2445},{"adult":false,"backdrop_path":"/qjTqY5coNiz6sVtPng40IzltsoN.jpg","genre_ids":[16,10751,35,12],"id":1084244,"title":"Toy Story 5","original_language":"en","original_title":"Toy Story 5","overview":"When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.","popularity":658.6359,"poster_path":"/sfQtVlIHljToOwYjhe21KPGzZWK.jpg","release_date":"2026-06-17","softcore":false,"video":false,"vote_average":7.397,"vote_count":537},{"adult":false,"backdrop_path":"/s6ly8laenkHWlIBRkLSfIuEMLC6.jpg","genre_ids":[878,53],"id":1275779,"title":"Disclosure Day","original_language":"en","original_title":"Disclosure Day","overview":"A cybersecurity expert becomes a whistleblower after uncovering secrets about aliens, putting him on the run from a corporation. Meanwhile, a meteorologist experiencing strange phenomena joins forces with him to prove there's life beyond our understanding.","popularity":496.6377,"poster_path":"/9XKXO68h0KGMCQ9ZZEdP0DWfcXS.jpg","release_date":"2026-06-10","softcore":false,"video":false,"vote_average":6.684,"vote_count":836},{"adult":false,"backdrop_path":"/mCpwRayjXMFzKHbjbzc5JRKfq1O.jpg","genre_ids":[27,9648,878],"id":1083381,"title":"Backrooms","original_language":"en","original_title":"Backrooms","overview":"A strange doorway appears in the basement of a furniture showroom.","popularity":466.6709,"poster_path":"/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg","release_date":"2026-05-27","softcore":false,"video":false,"vote_average":6.823,"vote_count":957},{"adult":false,"backdrop_path":"/xWBiXclrRmTggQHMRsIn84YHavs.jpg","genre_ids":[35],"id":1273221,"title":"Scary Movie","original_language":"en","original_title":"Scary Movie","overview":"Twenty-six years after outrunning a suspiciously familiar masked killer, the Core Four are back in the killer's crosshairs and no horror movie IP is safe.","popularity":462.1724,"poster_path":"/1KlYdWoOrbL5ux357rW9LC155qw.jpg","release_date":"2026-06-03","softcore":false,"video":false,"vote_average":5.407,"vote_count":430},{"adult":false,"backdrop_path":"/Af907x5h9W1wVis8XrSd7ynTWuy.jpg","genre_ids":[35,18],"id":1314481,"title":"The Devil Wears Prada 2","original_language":"en","original_title":"The Devil Wears Prada 2","overview":"Andy Sachs returns to Runway as Miranda Priestly navigates a new media landscape and Runway's position within. The duo reconnect with former assistant Emily Charlton, now the head of a luxury brand that possesses funding which could ensure Runway's survival.","popularity":349.8566,"poster_path":"/fCAURTUx3YfsJ8k9I0UamjSILiR.jpg","release_date":"2026-04-29","softcore":false,"video":false,"vote_average":7.015,"vote_count":1340},{"adult":false,"backdrop_path":"/1AVF2fAevpfi2HP6AEpptG1kg8R.jpg","genre_ids":[28,80,53],"id":1280738,"title":"The Furious","original_language":"zh","original_title":"火遮眼","overview":"After Wang Wei's daughter is kidnapped by a criminal network and he receives no help from the corrupt police, Wei sets out to find her himself. His only ally is Navin, a relentless journalist whose wife has mysteriously disappeared. Fueled by a furious vengeance, the unlikely duo ruthlessly battle the kidnappers in this explosive martial arts showdown.","popularity":275.0029,"poster_path":"/zP19YO60jwEsfKd5Qf1UvA5uJu8.jpg","release_date":"2026-06-10","softcore":false,"video":false,"vote_average":7.643,"vote_count":119},{"adult":false,"backdrop_path":"/qJ2KSHJhlFvASBMLbGuP7OFMaFg.jpg","genre_ids":[53,28,80],"id":1413976,"title":"Citizen Vigilante","original_language":"en","original_title":"Citizen Vigilante","overview":"A man takes justice into his own hands, hunting down criminals. His vigilante crusade makes him a social media star but puts him at odds with the local police chief.","popularity":254.4411,"poster_path":"/6LmJD3Wohe0g4U62wgi7RyJqfE4.jpg","release_date":"2026-06-19","softcore":false,"video":false,"vote_average":6.558,"vote_count":216},{"adult":false,"backdrop_path":"/szKv713FcUXx6hcfdY369vtkmzr.jpg","genre_ids":[27,53],"id":1127384,"title":"Deep Water","original_language":"en","original_title":"Deep Water","overview":"A group of international passengers on a flight from Los Angeles to Shanghai is forced to make an emergency landing in shark-infested waters. The terrified group is forced to work together and overcome their differences if they hope to escape their sinking plane and the frenzy of sharks drawn to the wreckage.","popularity":214.656,"poster_path":"/kjcuS7xaRyqRjVaVcH4t0qHshuX.jpg","release_date":"2026-04-30","softcore":false,"video":false,"vote_average":7.181,"vote_count":171},{"adult":false,"backdrop_path":"/1x9e0qWonw634NhIsRdvnneeqvN.jpg","genre_ids":[10749],"id":1523145,"title":"Your Heart Will Be Broken","original_language":"ru","original_title":"Твоё сердце будет разбито","overview":"High school student Polina is saved from bullying at her new school and makes a deal with the main bully Bars: he must pretend to be her boyfriend and protect her, and she must do everything he says. During this game, the couple develops real feelings, but her family and classmates have reasons to separate the lovers.","popularity":212.5677,"poster_path":"/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg","release_date":"2026-03-26","softcore":false,"video":false,"vote_average":7.079,"vote_count":108},{"adult":false,"backdrop_path":"/3pDfu71mrzSuFYyIfnKEjt8z4BC.jpg","genre_ids":[27,53],"id":1368314,"title":"Passenger","original_language":"en","original_title":"Passenger","overview":"After a young couple witnesses a gruesome highway accident, they soon realize they did not leave the crash scene alone, as a demonic presence called the Passenger that won't stop until it claims them both turns their van life adventure into a nightmare.","popularity":184.6921,"poster_path":"/2sOEJzhPzjTkZSlPbGxOJ7xgIyS.jpg","release_date":"2026-05-20","softcore":false,"video":false,"vote_average":5.671,"vote_count":143},{"adult":false,"backdrop_path":"/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg","genre_ids":[10402,18],"id":936075,"title":"Michael","original_language":"en","original_title":"Michael","overview":"The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.","popularity":178.3103,"poster_path":"/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg","release_date":"2026-04-22","softcore":false,"video":false,"vote_average":8.702,"vote_count":3372},{"adult":false,"backdrop_path":"/uLu8zcwmR7qjkkF3zkScm6Sjh2v.jpg","genre_ids":[18],"id":5721,"title":"Vixen!","original_language":"en","original_title":"Vixen!","overview":"In a Canadian mountain resort, Vixen Palmer resides with her naive pilot husband Tom. While he's away flying in tourists, she sleeps with practically everybody including a husband and his wife, and even her biker brother. However, the only one she won't bed is her brother's friend... who is Black.","popularity":176.727,"poster_path":"/9KMZWDA3xTrlgrScqdMisINQmsh.jpg","release_date":"1968-10-15","softcore":false,"video":false,"vote_average":5.524,"vote_count":104},{"adult":false,"backdrop_path":"/jLuGZc84MvPYCQomQg9DI72mstt.jpg","genre_ids":[12,80,9648],"id":1202033,"title":"Enola Holmes 3","original_language":"en","original_title":"Enola Holmes 3","overview":"Adventure follows detective Enola Holmes to Malta, where her plans to tie the knot unravel when Sherlock's disappearance plunges her into a perilous case.","popularity":169.8106,"poster_path":"/7kRYHH9H9PjBFwz1FprbHB2AAjI.jpg","release_date":"2026-06-30","softcore":false,"video":false,"vote_average":7.016,"vote_count":310},{"adult":false,"backdrop_path":"/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg","genre_ids":[18,80],"id":278,"title":"The Shawshank Redemption","original_language":"en","original_title":"The Shawshank Redemption","overview":"Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.","popularity":166.9172,"poster_path":"/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg","release_date":"1994-09-23","softcore":false,"video":false,"vote_average":8.724,"vote_count":30724},{"adult":false,"backdrop_path":"/xMoXsOgF0hBP7iVj7ZPIrFtTeL3.jpg","genre_ids":[12,16,35,10751,14],"id":1315772,"title":"Minions & Monsters","original_language":"en","original_title":"Minions & Monsters","overview":"This is the rambunctious, ridiculous and totally true story of how the Minions conquered Hollywood, became movie stars, lost everything, unleashed monsters onto the world and then banded together to try and save the planet from the mayhem they had just created.","popularity":166.274,"poster_path":"/nz7i42yhLIJ4ve9JKgM6NthoLHO.jpg","release_date":"2026-06-24","softcore":false,"video":false,"vote_average":6.39,"vote_count":136},{"adult":false,"backdrop_path":"/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg","genre_ids":[878,12],"id":687163,"title":"Project Hail Mary","original_language":"en","original_title":"Project Hail Mary","overview":"Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.","popularity":164.3082,"poster_path":"/yihdXomYb5kTeSivtFndMy5iDmf.jpg","release_date":"2026-03-15","softcore":false,"video":false,"vote_average":8.675,"vote_count":5851},{"adult":false,"backdrop_path":"/mVHyU4pnu9b2LWByPGGM0GGCA1v.jpg","genre_ids":[28,53],"id":1279493,"title":"The Get Out","original_language":"en","original_title":"The Get Out","overview":"A nightclub owner is on the verge of leaving his dangerous past behind for retirement with his girlfriend. When masked gunmen rob him and he finds himself squeezed by ruthless cartels, a mysterious newcomer arrives with an interest in buying the business. With danger closing in from all sides, he must navigate a deadly web of deception, power, and survival  -  where escape may no longer be an option.","popularity":153.7142,"poster_path":"/zlkeH0s7dDxcnuPcHBqAyXFUxqN.jpg","release_date":"2026-06-18","softcore":false,"video":false,"vote_average":6.5,"vote_count":31},{"adult":false,"backdrop_path":"/4EAAwpylq313qrDqpCxulUrXBNF.jpg","genre_ids":[28,14,12],"id":931285,"title":"Mortal Kombat II","original_language":"en","original_title":"Mortal Kombat II","overview":"The fan favorite champions—now joined by Johnny Cage himself—are pitted against one another in the ultimate, no-holds barred, gory battle to defeat the dark rule of Shao Kahn that threatens the very existence of the Earthrealm and its defenders.","popularity":149.3051,"poster_path":"/hwRdDFIhaEmpRgoki805YvyyjZf.jpg","release_date":"2026-05-06","softcore":false,"video":false,"vote_average":7.976,"vote_count":1910},{"adult":false,"backdrop_path":"/jITuPW8zL9JmDnc7R24jpTtn2Qu.jpg","genre_ids":[18,10749],"id":11012,"title":"Damage","original_language":"en","original_title":"Damage","overview":"The life of a respected British politician at the height of his career crumbles when he becomes obsessed with his son's lover.","popularity":141.4918,"poster_path":"/alf3JOPP7EYP0iO24gwe5YfRnqo.jpg","release_date":"1992-12-02","softcore":false,"video":false,"vote_average":6.6,"vote_count":701}],"total_pages":57908,"total_results":1158155}

In [ ]:
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg,"[27, 53]",1339713,Obsession,en,Obsession,"After breaking the mysterious ""One Wish Willow...",722.1192,/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg,2026-05-13,False,False,8.271,2445
1,False,/qjTqY5coNiz6sVtPng40IzltsoN.jpg,"[16, 10751, 35, 12]",1084244,Toy Story 5,en,Toy Story 5,When Bonnie receives a Lilypad tablet as a gif...,658.6359,/sfQtVlIHljToOwYjhe21KPGzZWK.jpg,2026-06-17,False,False,7.397,537
2,False,/s6ly8laenkHWlIBRkLSfIuEMLC6.jpg,"[878, 53]",1275779,Disclosure Day,en,Disclosure Day,A cybersecurity expert becomes a whistleblower...,496.6377,/9XKXO68h0KGMCQ9ZZEdP0DWfcXS.jpg,2026-06-10,False,False,6.684,836
3,False,/mCpwRayjXMFzKHbjbzc5JRKfq1O.jpg,"[27, 9648, 878]",1083381,Backrooms,en,Backrooms,A strange doorway appears in the basement of a...,466.6709,/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg,2026-05-27,False,False,6.823,957
4,False,/xWBiXclrRmTggQHMRsIn84YHavs.jpg,[35],1273221,Scary Movie,en,Scary Movie,Twenty-six years after outrunning a suspicious...,462.1724,/1KlYdWoOrbL5ux357rW9LC155qw.jpg,2026-06-03,False,False,5.407,430
5,False,/Af907x5h9W1wVis8XrSd7ynTWuy.jpg,"[35, 18]",1314481,The Devil Wears Prada 2,en,The Devil Wears Prada 2,Andy Sachs returns to Runway as Miranda Priest...,349.8566,/fCAURTUx3YfsJ8k9I0UamjSILiR.jpg,2026-04-29,False,False,7.015,1340
6,False,/1AVF2fAevpfi2HP6AEpptG1kg8R.jpg,"[28, 80, 53]",1280738,The Furious,zh,火遮眼,After Wang Wei's daughter is kidnapped by a cr...,275.0029,/zP19YO60jwEsfKd5Qf1UvA5uJu8.jpg,2026-06-10,False,False,7.643,119
7,False,/qJ2KSHJhlFvASBMLbGuP7OFMaFg.jpg,"[53, 28, 80]",1413976,Citizen Vigilante,en,Citizen Vigilante,"A man takes justice into his own hands, huntin...",254.4411,/6LmJD3Wohe0g4U62wgi7RyJqfE4.jpg,2026-06-19,False,False,6.558,216
8,False,/szKv713FcUXx6hcfdY369vtkmzr.jpg,"[27, 53]",1127384,Deep Water,en,Deep Water,A group of international passengers on a fligh...,214.6560,/kjcuS7xaRyqRjVaVcH4t0qHshuX.jpg,2026-04-30,False,False,7.181,171
9,False,/1x9e0qWonw634NhIsRdvnneeqvN.jpg,[10749],1523145,Your Heart Will Be Broken,ru,Твоё сердце будет разбито,High school student Polina is saved from bully...,212.5677,/7wIBfBl2gejt6xHxNSK0reVIm7E.jpg,2026-03-26,False,False,7.079,108
10,False,/3pDfu71mrzSuFYyIfnKEjt8z4BC.jpg,"[27, 53]",1368314,Passenger,en,Passenger,After a young couple witnesses a gruesome high...,184.6921,/2sOEJzhPzjTkZSlPbGxOJ7xgIyS.jpg,2026-05-20,False,False,5.671,143
11,False,/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg,"[10402, 18]",936075,Michael,en,Michael,"The story of Michael Jackson, one of the most ...",178.3103,/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg,2026-04-22,False,False,8.702,3372
12,False,/uLu8zcwmR7qjkkF3zkScm6Sjh2v.jpg,[18],5721,Vixen!,en,Vixen!,"In a Canadian mountain resort, Vixen Palmer re...",176.7270,/9KMZWDA3xTrlgrScqdMisINQmsh.jpg,1968-10-15,False,False,5.524,104
13,False,/jLuGZc84MvPYCQomQg9DI72mstt.jpg,"[12, 80, 9648]",1202033,Enola Holmes 3,en,Enola Holmes 3,Adventure follows detective Enola Holmes to Ma...,169.8106,/7kRYHH9H9PjBFwz1FprbHB2AAjI.jpg,2026-06-30,False,False,7.016,310
14,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,166.9172,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.724,30724
15,False,/xMoXsOgF0hBP7iVj7ZPIrFtTeL3.jpg,"[12, 16, 35, 10751, 14]",1315772,Minions & Monsters,en,Minions & Monsters,"This is the rambunctious, ridiculous and total...",166.2740,/nz7i42yhLIJ4ve9JKgM6NthoLHO.jpg,2026-06-24,False,False,6.390,136
16,False,/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg,"[878, 12]",687163,Project Hail Mary,en,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,164.3082,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,2026-03-15,False,False,8.675,5851
17,False,/mVHyU4pnu9b2LWByPGGM0GGCA1v.jpg,"[28, 53]",1279493,The Get Out,en,The Get Out,A nightclub owner is on the verge of leaving h...,153.7142,/zlkeH0s7dDxcnuPcHBqAyXFUxqN.jpg,2026-06-18,False,False,6.500,31
18,False,/4EAAwpylq313qrDqpCxulUrXBNF.jpg,"[28, 14, 12]",931285,Mortal Kombat II,en,Mortal Kombat II,The fan favorite champions—now joined by Johnn...,149.3051,/hwRdDFIhaEmpRgoki805YvyyjZf.jpg,2026-05-06,False,False,7.976,1910
19,False,/jITuPW8zL9JmDnc7R24jpTtn2Qu.jpg,"[18, 10749]",11012,Damage,en,Damage,The life of a respected British politician at ...,141.4918,/alf3JOPP7EYP0iO24gwe5YfRnqo.jpg,1992-12-02,False,False,6.600,701

In [ ]:
import requests

url = "https://api.themoviedb.org/3/trending/movie/day?api_key=107df16507f64dac79467a3685d428ad&language=en-US"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxMDdkZjE2NTA3ZjY0ZGFjNzk0NjdhMzY4NWQ0MjhhZCIsIm5iZiI6MTc1ODgwMzE0Mi4zOTIsInN1YiI6IjY4ZDUzNGM2ZmU3ZjYxMWQwZDE5ZGNhMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.XvYrspn1p-9vslUcIZN3DY3FT2uu3m8W1tL9N6inFqQ"
}

response = requests.get(url, headers=headers)

print(response.text)

{"page":1,"results":[{"adult":false,"backdrop_path":"/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg","id":1339713,"title":"Obsession","original_title":"Obsession","overview":"After breaking the mysterious \"One Wish Willow\" to win his crush's heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.","poster_path":"/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg","media_type":"movie","original_language":"en","genre_ids":[27,53],"popularity":722.1192,"release_date":"2026-05-13","softcore":false,"video":false,"vote_average":8.273,"vote_count":2453},{"adult":false,"backdrop_path":"/1AVF2fAevpfi2HP6AEpptG1kg8R.jpg","id":1280738,"title":"The Furious","original_title":"火遮眼","overview":"After Wang Wei's daughter is kidnapped by a criminal network and he receives no help from the corrupt police, Wei sets out to find her himself. His only ally is Navin, a relentless journalist whose wife has mysteriously disappeared. Fueled by a furious vengeance, the unlikely duo ruthlessly battle the kidnappers in this explosive martial arts showdown.","poster_path":"/zP19YO60jwEsfKd5Qf1UvA5uJu8.jpg","media_type":"movie","original_language":"zh","genre_ids":[28,80,53],"popularity":275.0029,"release_date":"2026-06-10","softcore":false,"video":false,"vote_average":7.6,"vote_count":119},{"adult":false,"backdrop_path":"/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg","id":1108427,"title":"Moana","original_title":"Moana","overview":"Moana answers the Ocean's call and, for the first time, voyages beyond the reef of her island of Motunui with the infamous demigod Maui on an unforgettable journey to restore prosperity to her people.","poster_path":"/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg","media_type":"movie","original_language":"en","genre_ids":[10751,14,35,12],"popularity":98.5184,"release_date":"2026-07-08","softcore":false,"video":false,"vote_average":4.758,"vote_count":33},{"adult":false,"backdrop_path":"/A5Tz6ogGt4VV8NESG9oWVct5bo1.jpg","id":1212763,"title":"Evil Dead Burn","original_title":"Evil Dead Burn","overview":"After the loss of her husband, a woman seeks solace with her in-laws. As one by one they transform into deadites, she comes to discover that the vows she took in life - survive even in death.","poster_path":"/ztadKzIIR0ERYqpHteaPFtk7inP.jpg","media_type":"movie","original_language":"en","genre_ids":[27,53],"popularity":58.8586,"release_date":"2026-07-07","softcore":false,"video":false,"vote_average":7.3,"vote_count":25},{"adult":false,"backdrop_path":"/m3Pom6pbD51bBv3syz8NMHda3fz.jpg","id":1368337,"title":"The Odyssey","original_title":"The Odyssey","overview":"Odysseus, the legendary King of Ithaca, embarks on a long and perilous journey home following the Trojan War. Throughout his voyage, he is forced to confront the whims of gods, mythological monsters, and trials that stretch both his cunning and his humanity to the breaking point.","poster_path":"/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg","media_type":"movie","original_language":"en","genre_ids":[12,28,14],"popularity":95.9651,"release_date":"2026-07-15","softcore":false,"video":false,"vote_average":5.5,"vote_count":4},{"adult":false,"backdrop_path":"/mCpwRayjXMFzKHbjbzc5JRKfq1O.jpg","id":1083381,"title":"Backrooms","original_title":"Backrooms","overview":"A strange doorway appears in the basement of a furniture showroom.","poster_path":"/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg","media_type":"movie","original_language":"en","genre_ids":[27,9648,878],"popularity":466.6709,"release_date":"2026-05-27","softcore":false,"video":false,"vote_average":6.82,"vote_count":959},{"adult":false,"backdrop_path":"/6tByIjKn3VLEVHhfpiNNWrnSIOM.jpg","id":1710008,"title":"Nothing to Lose","original_title":"Jusqu'au bout","overview":"She gave everything to become a mother, so when her young son falls ill, Jada will stop at  nothing to find a donor and save him — no matter the cost.","poster_path":"/3SKN8QZptMm8KfCCQtEmyh1Zkgz.jpg","media_type":"movie","original_language":"fr","genre_ids":[18,28],"popularity":28.5307,"release_date":"2026-07-08","softcore":false,"video":false,"vote_average":4.25,"vote_count":12},{"adult":false,"backdrop_path":"/3pDfu71mrzSuFYyIfnKEjt8z4BC.jpg","id":1368314,"title":"Passenger","original_title":"Passenger","overview":"After a young couple witnesses a gruesome highway accident, they soon realize they did not leave the crash scene alone, as a demonic presence called the Passenger that won't stop until it claims them both turns their van life adventure into a nightmare.","poster_path":"/2sOEJzhPzjTkZSlPbGxOJ7xgIyS.jpg","media_type":"movie","original_language":"en","genre_ids":[27,53],"popularity":184.6921,"release_date":"2026-05-20","softcore":false,"video":false,"vote_average":5.721,"vote_count":147},{"adult":false,"backdrop_path":"/qjTqY5coNiz6sVtPng40IzltsoN.jpg","id":1084244,"title":"Toy Story 5","original_title":"Toy Story 5","overview":"When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.","poster_path":"/sfQtVlIHljToOwYjhe21KPGzZWK.jpg","media_type":"movie","original_language":"en","genre_ids":[16,10751,35,12],"popularity":658.6359,"release_date":"2026-06-17","softcore":false,"video":false,"vote_average":7.4,"vote_count":538},{"adult":false,"backdrop_path":"/i5E9H7Ik0u61ylDDTbmUpTL3Yw.jpg","id":1170608,"title":"Dune: Part Three","original_title":"Dune: Part Three","overview":"As Emperor, Paul Atreides grapples with the consequences of his rise to power as political conspiracies and a galaxy-spanning holy war threaten the future he alone can foresee.","poster_path":"/d43fvHQsIMa4kpyhKXw0haEJIvI.jpg","media_type":"movie","original_language":"en","genre_ids":[28,12,878],"popularity":18.7772,"release_date":"2026-12-16","softcore":false,"video":false,"vote_average":0.0,"vote_count":0},{"adult":false,"backdrop_path":"/vjMvFSmGUxEtqVdaZgvFee9XkZl.jpg","id":969681,"title":"Spider-Man: Brand New Day","original_title":"Spider-Man: Brand New Day","overview":"Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.","poster_path":"/yyB2VJEW3an2xCdcYCPQhn9QERR.jpg","media_type":"movie","original_language":"en","genre_ids":[878,28,12],"popularity":88.2917,"release_date":"2026-07-29","softcore":false,"video":false,"vote_average":0.0,"vote_count":0},{"adult":false,"backdrop_path":"/xMoXsOgF0hBP7iVj7ZPIrFtTeL3.jpg","id":1315772,"title":"Minions & Monsters","original_title":"Minions & Monsters","overview":"This is the rambunctious, ridiculous and totally true story of how the Minions conquered Hollywood, became movie stars, lost everything, unleashed monsters onto the world and then banded together to try and save the planet from the mayhem they had just created.","poster_path":"/nz7i42yhLIJ4ve9JKgM6NthoLHO.jpg","media_type":"movie","original_language":"en","genre_ids":[12,16,35,10751,14],"popularity":166.274,"release_date":"2026-06-24","softcore":false,"video":false,"vote_average":6.39,"vote_count":136},{"adult":false,"backdrop_path":"/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg","id":687163,"title":"Project Hail Mary","original_title":"Project Hail Mary","overview":"Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.","poster_path":"/yihdXomYb5kTeSivtFndMy5iDmf.jpg","media_type":"movie","original_language":"en","genre_ids":[878,12],"popularity":164.3082,"release_date":"2026-03-15","softcore":false,"video":false,"vote_average":8.674,"vote_count":5855},{"adult":false,"backdrop_path":"/kLA1GqiOEyVgXxgNqLoCr7bYcqu.jpg","id":950028,"title":"The Invite","original_title":"The Invite","overview":"Joe and Angela's marriage is on thin ice. When they invite their enigmatic upstairs neighbors for a dinner party, the night spirals into unexpected places. Have they reignited the spark or lit the match that burns it all down?","poster_path":"/b7Dr8Chzse8VagexAporUu2RtLx.jpg","media_type":"movie","original_language":"en","genre_ids":[18,35],"popularity":21.8105,"release_date":"2026-06-25","softcore":false,"video":false,"vote_average":7.875,"vote_count":24},{"adult":false,"backdrop_path":"/t6O6XWelu27BD0OmIDCCufZZT6d.jpg","id":1301421,"title":"The Sheep Detectives","original_title":"The Sheep Detectives","overview":"George Hardy is a shepherd who reads detective novels to his beloved sheep every night, assuming they can't possibly understand. But when a mysterious incident disrupts life on the farm, the sheep realize they must become the detectives. As they follow the clues and investigate human suspects, they prove that even sheep can be brilliant crime-solvers.","poster_path":"/TEaSqmI6TZQVimULYbingDIdXT.jpg","media_type":"movie","original_language":"en","genre_ids":[12,35,80,10751,9648],"popularity":118.7959,"release_date":"2026-04-30","softcore":false,"video":false,"vote_average":7.822,"vote_count":797},{"adult":false,"backdrop_path":"/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg","id":936075,"title":"Michael","original_title":"Michael","overview":"The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.","poster_path":"/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg","media_type":"movie","original_language":"en","genre_ids":[10402,18],"popularity":178.3103,"release_date":"2026-04-22","softcore":false,"video":false,"vote_average":8.702,"vote_count":3374},{"adult":false,"backdrop_path":"/Af907x5h9W1wVis8XrSd7ynTWuy.jpg","id":1314481,"title":"The Devil Wears Prada 2","original_title":"The Devil Wears Prada 2","overview":"Andy Sachs returns to Runway as Miranda Priestly navigates a new media landscape and Runway's position within. The duo reconnect with former assistant Emily Charlton, now the head of a luxury brand that possesses funding which could ensure Runway's survival.","poster_path":"/fCAURTUx3YfsJ8k9I0UamjSILiR.jpg","media_type":"movie","original_language":"en","genre_ids":[35,18],"popularity":349.8566,"release_date":"2026-04-29","softcore":false,"video":false,"vote_average":7.022,"vote_count":1343},{"adult":false,"backdrop_path":"/cbyslfazMuDUGt4W6QcO3cKq8xj.jpg","id":1081003,"title":"Supergirl","original_title":"Supergirl","overview":"When an unexpected and ruthless adversary strikes too close to home, Kara Zor-El, aka Supergirl, reluctantly joins forces with an unlikely companion on an epic, interstellar journey of vengeance and justice.","poster_path":"/moejGxR2haap29d9NQ7qe8x4eGj.jpg","media_type":"movie","original_language":"en","genre_ids":[28,12,878],"popularity":98.442,"release_date":"2026-06-24","softcore":false,"video":false,"vote_average":6.213,"vote_count":415},{"adult":false,"backdrop_path":"/s6ly8laenkHWlIBRkLSfIuEMLC6.jpg","id":1275779,"title":"Disclosure Day","original_title":"Disclosure Day","overview":"A cybersecurity expert becomes a whistleblower after uncovering secrets about aliens, putting him on the run from a corporation. Meanwhile, a meteorologist experiencing strange phenomena joins forces with him to prove there's life beyond our understanding.","poster_path":"/9XKXO68h0KGMCQ9ZZEdP0DWfcXS.jpg","media_type":"movie","original_language":"en","genre_ids":[878,53],"popularity":496.6377,"release_date":"2026-06-10","softcore":false,"video":false,"vote_average":6.7,"vote_count":837},{"adult":false,"backdrop_path":"/oPsRr7AfNLw6XaPuMpvkWK0bIUA.jpg","id":1057265,"title":"Peddi","original_title":"పెద్ది","overview":"In 1980s rural Andhra Pradesh, a spirited villager unites his community through sports to defend their pride against a powerful rivals.","poster_path":"/83jbWhsxnvirk0QKTIczYYT578A.jpg","media_type":"movie","original_language":"te","genre_ids":[28,18],"popularity":18.3982,"release_date":"2026-06-03","softcore":false,"video":false,"vote_average":6.1,"vote_count":54}],"total_pages":500,"total_results":10000}

In [ ]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg',
   'id': 1339713,
   'title': 'Obsession',
   'original_title': 'Obsession',
   'overview': 'After breaking the mysterious "One Wish Willow" to win his crush\'s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.',
   'poster_path': '/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27, 53],
   'popularity': 722.1192,
   'release_date': '2026-05-13',
   'softcore': False,
   'video': False,
   'vote_average': 8.273,
   'vote_count': 2453},
  {'adult': False,
   'backdrop_path': '/1AVF2fAevpfi2HP6AEpptG1kg8R.jpg',
   'id': 1280738,
   'title': 'The Furious',
   'original_title': '火遮眼',
   'overview': "After Wang Wei's daughter is kidnapped by a criminal network and he receives no help from the corrupt police, Wei sets out to find her himself. His only ally is Navin, a relentless journalist whose wife has mysteriously disappeared. Fueled by a furious vengeance, the unlikely duo ruthlessly battle the kidnappers in this explosive martial arts showdown.",
   'poster_path': '/zP19YO60jwEsfKd5Qf1UvA5uJu8.jpg',
   'media_type': 'movie',
   'original_language': 'zh',
   'genre_ids': [28, 80, 53],
   'popularity': 275.0029,
   'release_date': '2026-06-10',
   'softcore': False,
   'video': False,
   'vote_average': 7.6,
   'vote_count': 119},
  {'adult': False,
   'backdrop_path': '/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg',
   'id': 1108427,
   'title': 'Moana',
   'original_title': 'Moana',
   'overview': "Moana answers the Ocean's call and, for the first time, voyages beyond the reef of her island of Motunui with the infamous demigod Maui on an unforgettable journey to restore prosperity to her people.",
   'poster_path': '/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [10751, 14, 35, 12],
   'popularity': 98.5184,
   'release_date': '2026-07-08',
   'softcore': False,
   'video': False,
   'vote_average': 4.758,
   'vote_count': 33},
  {'adult': False,
   'backdrop_path': '/A5Tz6ogGt4VV8NESG9oWVct5bo1.jpg',
   'id': 1212763,
   'title': 'Evil Dead Burn',
   'original_title': 'Evil Dead Burn',
   'overview': 'After the loss of her husband, a woman seeks solace with her in-laws. As one by one they transform into deadites, she comes to discover that the vows she took in life - survive even in death.',
   'poster_path': '/ztadKzIIR0ERYqpHteaPFtk7inP.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27, 53],
   'popularity': 58.8586,
   'release_date': '2026-07-07',
   'softcore': False,
   'video': False,
   'vote_average': 7.3,
   'vote_count': 25},
  {'adult': False,
   'backdrop_path': '/m3Pom6pbD51bBv3syz8NMHda3fz.jpg',
   'id': 1368337,
   'title': 'The Odyssey',
   'original_title': 'The Odyssey',
   'overview': 'Odysseus, the legendary King of Ithaca, embarks on a long and perilous journey home following the Trojan War. Throughout his voyage, he is forced to confront the whims of gods, mythological monsters, and trials that stretch both his cunning and his humanity to the breaking point.',
   'poster_path': '/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [12, 28, 14],
   'popularity': 95.9651,
   'release_date': '2026-07-15',
   'softcore': False,
   'video': False,
   'vote_average': 5.5,
   'vote_count': 4},
  {'adult': False,
   'backdrop_path': '/mCpwRayjXMFzKHbjbzc5JRKfq1O.jpg',
   'id': 1083381,
   'title': 'Backrooms',
   'original_title': 'Backrooms',
   'overview': 'A strange doorway appears in the basement of a furniture showroom.',
   'poster_path': '/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27, 9648, 878],
   'popularity': 466.6709,
   'release_date': '2026-05-27',
   'softcore': False,
   'video': False,
   'vote_average': 6.82,
   'vote_count': 959},
  {'adult': False,
   'backdrop_path': '/6tByIjKn3VLEVHhfpiNNWrnSIOM.jpg',
   'id': 1710008,
   'title': 'Nothing to Lose',
   'original_title': "Jusqu'au bout",
   'overview': 'She gave everything to become a mother, so when her young son falls ill, Jada will stop at  nothing to find a donor and save him — no matter the cost.',
   'poster_path': '/3SKN8QZptMm8KfCCQtEmyh1Zkgz.jpg',
   'media_type': 'movie',
   'original_language': 'fr',
   'genre_ids': [18, 28],
   'popularity': 28.5307,
   'release_date': '2026-07-08',
   'softcore': False,
   'video': False,
   'vote_average': 4.25,
   'vote_count': 12},
  {'adult': False,
   'backdrop_path': '/3pDfu71mrzSuFYyIfnKEjt8z4BC.jpg',
   'id': 1368314,
   'title': 'Passenger',
   'original_title': 'Passenger',
   'overview': "After a young couple witnesses a gruesome highway accident, they soon realize they did not leave the crash scene alone, as a demonic presence called the Passenger that won't stop until it claims them both turns their van life adventure into a nightmare.",
   'poster_path': '/2sOEJzhPzjTkZSlPbGxOJ7xgIyS.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27, 53],
   'popularity': 184.6921,
   'release_date': '2026-05-20',
   'softcore': False,
   'video': False,
   'vote_average': 5.721,
   'vote_count': 147},
  {'adult': False,
   'backdrop_path': '/qjTqY5coNiz6sVtPng40IzltsoN.jpg',
   'id': 1084244,
   'title': 'Toy Story 5',
   'original_title': 'Toy Story 5',
   'overview': "When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.",
   'poster_path': '/sfQtVlIHljToOwYjhe21KPGzZWK.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [16, 10751, 35, 12],
   'popularity': 658.6359,
   'release_date': '2026-06-17',
   'softcore': False,
   'video': False,
   'vote_average': 7.4,
   'vote_count': 538},
  {'adult': False,
   'backdrop_path': '/i5E9H7Ik0u61ylDDTbmUpTL3Yw.jpg',
   'id': 1170608,
   'title': 'Dune: Part Three',
   'original_title': 'Dune: Part Three',
   'overview': 'As Emperor, Paul Atreides grapples with the consequences of his rise to power as political conspiracies and a galaxy-spanning holy war threaten the future he alone can foresee.',
   'poster_path': '/d43fvHQsIMa4kpyhKXw0haEJIvI.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [28, 12, 878],
   'popularity': 18.7772,
   'release_date': '2026-12-16',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/vjMvFSmGUxEtqVdaZgvFee9XkZl.jpg',
   'id': 969681,
   'title': 'Spider-Man: Brand New Day',
   'original_title': 'Spider-Man: Brand New Day',
   'overview': "Fighting crime full-time as Spider-Man in a world that doesn't remember him—and the pressure of seeing his old friends move on without him—sparks a change in Peter Parker he may not have the power to control. But that transformation might also be the only thing that can stop a shocking new threat to the city and those he loves - a powerful villain no one can even see.",
   'poster_path': '/yyB2VJEW3an2xCdcYCPQhn9QERR.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [878, 28, 12],
   'popularity': 88.2917,
   'release_date': '2026-07-29',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/xMoXsOgF0hBP7iVj7ZPIrFtTeL3.jpg',
   'id': 1315772,
   'title': 'Minions & Monsters',
   'original_title': 'Minions & Monsters',
   'overview': 'This is the rambunctious, ridiculous and totally true story of how the Minions conquered Hollywood, became movie stars, lost everything, unleashed monsters onto the world and then banded together to try and save the planet from the mayhem they had just created.',
   'poster_path': '/nz7i42yhLIJ4ve9JKgM6NthoLHO.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [12, 16, 35, 10751, 14],
   'popularity': 166.274,
   'release_date': '2026-06-24',
   'softcore': False,
   'video': False,
   'vote_average': 6.39,
   'vote_count': 136},
  {'adult': False,
   'backdrop_path': '/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg',
   'id': 687163,
   'title': 'Project Hail Mary',
   'original_title': 'Project Hail Mary',
   'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
   'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [878, 12],
   'popularity': 164.3082,
   'release_date': '2026-03-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.674,
   'vote_count': 5855},
  {'adult': False,
   'backdrop_path': '/kLA1GqiOEyVgXxgNqLoCr7bYcqu.jpg',
   'id': 950028,
   'title': 'The Invite',
   'original_title': 'The Invite',
   'overview': "Joe and Angela's marriage is on thin ice. When they invite their enigmatic upstairs neighbors for a dinner party, the night spirals into unexpected places. Have they reignited the spark or lit the match that burns it all down?",
   'poster_path': '/b7Dr8Chzse8VagexAporUu2RtLx.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [18, 35],
   'popularity': 21.8105,
   'release_date': '2026-06-25',
   'softcore': False,
   'video': False,
   'vote_average': 7.875,
   'vote_count': 24},
  {'adult': False,
   'backdrop_path': '/t6O6XWelu27BD0OmIDCCufZZT6d.jpg',
   'id': 1301421,
   'title': 'The Sheep Detectives',
   'original_title': 'The Sheep Detectives',
   'overview': "George Hardy is a shepherd who reads detective novels to his beloved sheep every night, assuming they can't possibly understand. But when a mysterious incident disrupts life on the farm, the sheep realize they must become the detectives. As they follow the clues and investigate human suspects, they prove that even sheep can be brilliant crime-solvers.",
   'poster_path': '/TEaSqmI6TZQVimULYbingDIdXT.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [12, 35, 80, 10751, 9648],
   'popularity': 118.7959,
   'release_date': '2026-04-30',
   'softcore': False,
   'video': False,
   'vote_average': 7.822,
   'vote_count': 797},
  {'adult': False,
   'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
   'id': 936075,
   'title': 'Michael',
   'original_title': 'Michael',
   'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
   'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [10402, 18],
   'popularity': 178.3103,
   'release_date': '2026-04-22',
   'softcore': False,
   'video': False,
   'vote_average': 8.702,
   'vote_count': 3374},
  {'adult': False,
   'backdrop_path': '/Af907x5h9W1wVis8XrSd7ynTWuy.jpg',
   'id': 1314481,
   'title': 'The Devil Wears Prada 2',
   'original_title': 'The Devil Wears Prada 2',
   'overview': "Andy Sachs returns to Runway as Miranda Priestly navigates a new media landscape and Runway's position within. The duo reconnect with former assistant Emily Charlton, now the head of a luxury brand that possesses funding which could ensure Runway's survival.",
   'poster_path': '/fCAURTUx3YfsJ8k9I0UamjSILiR.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [35, 18],
   'popularity': 349.8566,
   'release_date': '2026-04-29',
   'softcore': False,
   'video': False,
   'vote_average': 7.022,
   'vote_count': 1343},
  {'adult': False,
   'backdrop_path': '/cbyslfazMuDUGt4W6QcO3cKq8xj.jpg',
   'id': 1081003,
   'title': 'Supergirl',
   'original_title': 'Supergirl',
   'overview': 'When an unexpected and ruthless adversary strikes too close to home, Kara Zor-El, aka Supergirl, reluctantly joins forces with an unlikely companion on an epic, interstellar journey of vengeance and justice.',
   'poster_path': '/moejGxR2haap29d9NQ7qe8x4eGj.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [28, 12, 878],
   'popularity': 98.442,
   'release_date': '2026-06-24',
   'softcore': False,
   'video': False,
   'vote_average': 6.213,
   'vote_count': 415},
  {'adult': False,
   'backdrop_path': '/s6ly8laenkHWlIBRkLSfIuEMLC6.jpg',
   'id': 1275779,
   'title': 'Disclosure Day',
   'original_title': 'Disclosure Day',
   'overview': "A cybersecurity expert becomes a whistleblower after uncovering secrets about aliens, putting him on the run from a corporation. Meanwhile, a meteorologist experiencing strange phenomena joins forces with him to prove there's life beyond our understanding.",
   'poster_path': '/9XKXO68h0KGMCQ9ZZEdP0DWfcXS.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [878, 53],
   'popularity': 496.6377,
   'release_date': '2026-06-10',
   'softcore': False,
   'video': False,
   'vote_average': 6.7,
   'vote_count': 837},
  {'adult': False,
   'backdrop_path': '/oPsRr7AfNLw6XaPuMpvkWK0bIUA.jpg',
   'id': 1057265,
   'title': 'Peddi',
   'original_title': 'పెద్ది',
   'overview': 'In 1980s rural Andhra Pradesh, a spirited villager unites his community through sports to defend their pride against a powerful rivals.',
   'poster_path': '/83jbWhsxnvirk0QKTIczYYT578A.jpg',
   'media_type': 'movie',
   'original_language': 'te',
   'genre_ids': [28, 18],
   'popularity': 18.3982,
   'release_date': '2026-06-03',
   'softcore': False,
   'video': False,
   'vote_average': 6.1,
   'vote_count': 54}],
 'total_pages': 500,
 'total_results': 10000}

In [ ]:
tr_mdb=pd.DataFrame(response.json()['results'])

In [ ]:
tr_mdb

,adult,backdrop_path,id,title,original_title,overview,poster_path,media_type,original_language,genre_ids,popularity,release_date,softcore,video,vote_average,vote_count
0,False,/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg,1339713,Obsession,Obsession,"After breaking the mysterious ""One Wish Willow...",/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg,movie,en,"[27, 53]",722.1192,2026-05-13,False,False,8.273,2453
1,False,/1AVF2fAevpfi2HP6AEpptG1kg8R.jpg,1280738,The Furious,火遮眼,After Wang Wei's daughter is kidnapped by a cr...,/zP19YO60jwEsfKd5Qf1UvA5uJu8.jpg,movie,zh,"[28, 80, 53]",275.0029,2026-06-10,False,False,7.600,119
2,False,/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg,1108427,Moana,Moana,"Moana answers the Ocean's call and, for the fi...",/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg,movie,en,"[10751, 14, 35, 12]",98.5184,2026-07-08,False,False,4.758,33
3,False,/A5Tz6ogGt4VV8NESG9oWVct5bo1.jpg,1212763,Evil Dead Burn,Evil Dead Burn,"After the loss of her husband, a woman seeks s...",/ztadKzIIR0ERYqpHteaPFtk7inP.jpg,movie,en,"[27, 53]",58.8586,2026-07-07,False,False,7.300,25
4,False,/m3Pom6pbD51bBv3syz8NMHda3fz.jpg,1368337,The Odyssey,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,movie,en,"[12, 28, 14]",95.9651,2026-07-15,False,False,5.500,4
5,False,/mCpwRayjXMFzKHbjbzc5JRKfq1O.jpg,1083381,Backrooms,Backrooms,A strange doorway appears in the basement of a...,/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg,movie,en,"[27, 9648, 878]",466.6709,2026-05-27,False,False,6.820,959
6,False,/6tByIjKn3VLEVHhfpiNNWrnSIOM.jpg,1710008,Nothing to Lose,Jusqu'au bout,"She gave everything to become a mother, so whe...",/3SKN8QZptMm8KfCCQtEmyh1Zkgz.jpg,movie,fr,"[18, 28]",28.5307,2026-07-08,False,False,4.250,12
7,False,/3pDfu71mrzSuFYyIfnKEjt8z4BC.jpg,1368314,Passenger,Passenger,After a young couple witnesses a gruesome high...,/2sOEJzhPzjTkZSlPbGxOJ7xgIyS.jpg,movie,en,"[27, 53]",184.6921,2026-05-20,False,False,5.721,147
8,False,/qjTqY5coNiz6sVtPng40IzltsoN.jpg,1084244,Toy Story 5,Toy Story 5,When Bonnie receives a Lilypad tablet as a gif...,/sfQtVlIHljToOwYjhe21KPGzZWK.jpg,movie,en,"[16, 10751, 35, 12]",658.6359,2026-06-17,False,False,7.400,538
9,False,/i5E9H7Ik0u61ylDDTbmUpTL3Yw.jpg,1170608,Dune: Part Three,Dune: Part Three,"As Emperor, Paul Atreides grapples with the co...",/d43fvHQsIMa4kpyhKXw0haEJIvI.jpg,movie,en,"[28, 12, 878]",18.7772,2026-12-16,False,False,0.000,0
10,False,/vjMvFSmGUxEtqVdaZgvFee9XkZl.jpg,969681,Spider-Man: Brand New Day,Spider-Man: Brand New Day,Fighting crime full-time as Spider-Man in a wo...,/yyB2VJEW3an2xCdcYCPQhn9QERR.jpg,movie,en,"[878, 28, 12]",88.2917,2026-07-29,False,False,0.000,0
11,False,/xMoXsOgF0hBP7iVj7ZPIrFtTeL3.jpg,1315772,Minions & Monsters,Minions & Monsters,"This is the rambunctious, ridiculous and total...",/nz7i42yhLIJ4ve9JKgM6NthoLHO.jpg,movie,en,"[12, 16, 35, 10751, 14]",166.2740,2026-06-24,False,False,6.390,136
12,False,/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg,687163,Project Hail Mary,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,movie,en,"[878, 12]",164.3082,2026-03-15,False,False,8.674,5855
13,False,/kLA1GqiOEyVgXxgNqLoCr7bYcqu.jpg,950028,The Invite,The Invite,Joe and Angela's marriage is on thin ice. When...,/b7Dr8Chzse8VagexAporUu2RtLx.jpg,movie,en,"[18, 35]",21.8105,2026-06-25,False,False,7.875,24
14,False,/t6O6XWelu27BD0OmIDCCufZZT6d.jpg,1301421,The Sheep Detectives,The Sheep Detectives,George Hardy is a shepherd who reads detective...,/TEaSqmI6TZQVimULYbingDIdXT.jpg,movie,en,"[12, 35, 80, 10751, 9648]",118.7959,2026-04-30,False,False,7.822,797
15,False,/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg,936075,Michael,Michael,"The story of Michael Jackson, one of the most ...",/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg,movie,en,"[10402, 18]",178.3103,2026-04-22,False,False,8.702,3374
16,False,/Af907x5h9W1wVis8XrSd7ynTWuy.jpg,1314481,The Devil Wears Prada 2,The Devil Wears Prada 2,Andy Sachs returns to Runway as Miranda Priest...,/fCAURTUx3YfsJ8k9I0UamjSILiR.jpg,movie,en,"[35, 18]",349.8566,2026-04-29,False,False,7.022,1343
17,False,/cbyslfazMuDUGt4W6QcO3cKq8xj.jpg,1081003,Supergirl,Supergirl,When an unexpected and ruthless adversary stri...,/moejGxR2haap29d9NQ7qe8x4eGj.jpg,movie,en,"[28, 12, 878]",98.4420,2026-06-24,False,False,6.213,415
18,False,/s6ly8laenkHWlIBRkLSfIuEMLC6.jpg,1275779,Disclosure Day,Disclosure Day,A cybersecurity expert becomes a whistleblower...,/9XKXO68h0KGMCQ9ZZEdP0DWfcXS.jpg,movie,en,"[878, 53]",496.6377,2026-06-10,False,False,6.700,837
19,False,/oPsRr7AfNLw6XaPuMpvkWK0bIUA.jpg,1057265,Peddi,పెద్ది,"In 1980s rural Andhra Pradesh, a spirited vill...",/83jbWhsxnvirk0QKTIczYYT578A.jpg,movie,te,"[28, 18]",18.3982,2026-06-03,False,False,6.100,54

In [ ]:
tr_mdb.to_csv('Top_Rated_Movies_2026.csv',index=False)

In [ ]:
import requests

url = "https://api.themoviedb.org/3/trending/all/day?language=en-US"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxMDdkZjE2NTA3ZjY0ZGFjNzk0NjdhMzY4NWQ0MjhhZCIsIm5iZiI6MTc1ODgwMzE0Mi4zOTIsInN1YiI6IjY4ZDUzNGM2ZmU3ZjYxMWQwZDE5ZGNhMCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.XvYrspn1p-9vslUcIZN3DY3FT2uu3m8W1tL9N6inFqQ"
}

response = requests.get(url, headers=headers)

print(response.text)

{"page":1,"results":[{"adult":false,"backdrop_path":"/fBieUo3SdItUrXZE16YxbpjwXIe.jpg","id":283304,"name":"Little House on the Prairie","original_name":"Little House on the Prairie","overview":"The close-knit Ingalls family builds a new life on the Western frontier, where the joys of nature and the struggle for survival are deeply intertwined.","poster_path":"/oWUGSadxC9vQPOCeHDDVfDezmQC.jpg","media_type":"tv","original_language":"en","genre_ids":[18,37,10751],"popularity":41.8913,"first_air_date":"2026-07-09","softcore":false,"vote_average":5.833,"vote_count":6,"origin_country":["US"]},{"adult":false,"backdrop_path":"/A5Tz6ogGt4VV8NESG9oWVct5bo1.jpg","id":1212763,"title":"Evil Dead Burn","original_title":"Evil Dead Burn","overview":"After the loss of her husband, a woman seeks solace with her in-laws. As one by one they transform into deadites, she comes to discover that the vows she took in life - survive even in death.","poster_path":"/ztadKzIIR0ERYqpHteaPFtk7inP.jpg","media_type":"movie","original_language":"en","genre_ids":[27,53],"popularity":58.8586,"release_date":"2026-07-07","softcore":false,"video":false,"vote_average":7.3,"vote_count":25},{"adult":false,"backdrop_path":"/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg","id":1339713,"title":"Obsession","original_title":"Obsession","overview":"After breaking the mysterious \"One Wish Willow\" to win his crush's heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.","poster_path":"/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg","media_type":"movie","original_language":"en","genre_ids":[27,53],"popularity":722.1192,"release_date":"2026-05-13","softcore":false,"video":false,"vote_average":8.274,"vote_count":2455},{"adult":false,"backdrop_path":"/1AVF2fAevpfi2HP6AEpptG1kg8R.jpg","id":1280738,"title":"The Furious","original_title":"火遮眼","overview":"After Wang Wei's daughter is kidnapped by a criminal network and he receives no help from the corrupt police, Wei sets out to find her himself. His only ally is Navin, a relentless journalist whose wife has mysteriously disappeared. Fueled by a furious vengeance, the unlikely duo ruthlessly battle the kidnappers in this explosive martial arts showdown.","poster_path":"/zP19YO60jwEsfKd5Qf1UvA5uJu8.jpg","media_type":"movie","original_language":"zh","genre_ids":[28,80,53],"popularity":275.0029,"release_date":"2026-06-10","softcore":false,"video":false,"vote_average":7.6,"vote_count":119},{"adult":false,"backdrop_path":"/m3Pom6pbD51bBv3syz8NMHda3fz.jpg","id":1368337,"title":"The Odyssey","original_title":"The Odyssey","overview":"Odysseus, the legendary King of Ithaca, embarks on a long and perilous journey home following the Trojan War. Throughout his voyage, he is forced to confront the whims of gods, mythological monsters, and trials that stretch both his cunning and his humanity to the breaking point.","poster_path":"/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg","media_type":"movie","original_language":"en","genre_ids":[12,28,14],"popularity":95.9651,"release_date":"2026-07-15","softcore":false,"video":false,"vote_average":5.5,"vote_count":4},{"adult":false,"backdrop_path":"/mCpwRayjXMFzKHbjbzc5JRKfq1O.jpg","id":1083381,"title":"Backrooms","original_title":"Backrooms","overview":"A strange doorway appears in the basement of a furniture showroom.","poster_path":"/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg","media_type":"movie","original_language":"en","genre_ids":[27,9648,878],"popularity":466.6709,"release_date":"2026-05-27","softcore":false,"video":false,"vote_average":6.82,"vote_count":959},{"adult":false,"backdrop_path":"/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg","id":1108427,"title":"Moana","original_title":"Moana","overview":"Moana answers the Ocean's call and, for the first time, voyages beyond the reef of her island of Motunui with the infamous demigod Maui on an unforgettable journey to restore prosperity to her people.","poster_path":"/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg","media_type":"movie","original_language":"en","genre_ids":[10751,14,35,12],"popularity":98.5184,"release_date":"2026-07-08","softcore":false,"video":false,"vote_average":4.758,"vote_count":33},{"adult":false,"backdrop_path":"/wK1SL5EUJ6Bq2UhDCRtT1FA1HdN.jpg","id":297826,"name":"Tomb Raider King","original_name":"도굴왕","overview":"Chaos ensues overnight when mysterious tombs suddenly surface, filled with divine relics granting overwhelming power, triggering a global power struggle to claim them for dominion. Among the havoc, a raider, Jooheon Suh, is betrayed and left for dead until a second chance brings him back years before the relics. Fueled by fury and future knowledge, he sets out to raid each tomb before they arise.","poster_path":"/xDW6cor12UD0b2IqboQWnrIn0UO.jpg","media_type":"tv","original_language":"ko","genre_ids":[16,10759,10765],"popularity":25.8928,"first_air_date":"2026-07-09","softcore":false,"vote_average":0.0,"vote_count":0,"origin_country":["KR"]},{"adult":false,"backdrop_path":"/3pDfu71mrzSuFYyIfnKEjt8z4BC.jpg","id":1368314,"title":"Passenger","original_title":"Passenger","overview":"After a young couple witnesses a gruesome highway accident, they soon realize they did not leave the crash scene alone, as a demonic presence called the Passenger that won't stop until it claims them both turns their van life adventure into a nightmare.","poster_path":"/2sOEJzhPzjTkZSlPbGxOJ7xgIyS.jpg","media_type":"movie","original_language":"en","genre_ids":[27,53],"popularity":184.6921,"release_date":"2026-05-20","softcore":false,"video":false,"vote_average":5.8,"vote_count":149},{"adult":false,"backdrop_path":"/i5E9H7Ik0u61ylDDTbmUpTL3Yw.jpg","id":1170608,"title":"Dune: Part Three","original_title":"Dune: Part Three","overview":"As Emperor, Paul Atreides grapples with the consequences of his rise to power as political conspiracies and a galaxy-spanning holy war threaten the future he alone can foresee.","poster_path":"/d43fvHQsIMa4kpyhKXw0haEJIvI.jpg","media_type":"movie","original_language":"en","genre_ids":[28,12,878],"popularity":18.7772,"release_date":"2026-12-16","softcore":false,"video":false,"vote_average":0.0,"vote_count":0},{"adult":false,"backdrop_path":"/feISh3qoREwIPWbSaLqqumbmh7m.jpg","id":322055,"name":"The Prosecutor's Proposal","original_name":"검사실의 제안","overview":"A victim’s son and a killer’s son reunite as a prosecutor and investigator, fighting systemic corruption while becoming each other's salvation.","poster_path":"/lK6DrnFecG0AsA8O5UqEYOrOArd.jpg","media_type":"tv","original_language":"ko","genre_ids":[9648,80,18],"popularity":244.8945,"first_air_date":"2026-06-25","softcore":false,"vote_average":5.0,"vote_count":4,"origin_country":["KR"]},{"adult":false,"backdrop_path":"/6tByIjKn3VLEVHhfpiNNWrnSIOM.jpg","id":1710008,"title":"Nothing to Lose","original_title":"Jusqu'au bout","overview":"She gave everything to become a mother, so when her young son falls ill, Jada will stop at  nothing to find a donor and save him — no matter the cost.","poster_path":"/3SKN8QZptMm8KfCCQtEmyh1Zkgz.jpg","media_type":"movie","original_language":"fr","genre_ids":[18,28],"popularity":28.5307,"release_date":"2026-07-08","softcore":false,"video":false,"vote_average":4.25,"vote_count":12},{"adult":false,"backdrop_path":"/xMoXsOgF0hBP7iVj7ZPIrFtTeL3.jpg","id":1315772,"title":"Minions & Monsters","original_title":"Minions & Monsters","overview":"This is the rambunctious, ridiculous and totally true story of how the Minions conquered Hollywood, became movie stars, lost everything, unleashed monsters onto the world and then banded together to try and save the planet from the mayhem they had just created.","poster_path":"/nz7i42yhLIJ4ve9JKgM6NthoLHO.jpg","media_type":"movie","original_language":"en","genre_ids":[12,16,35,10751,14],"popularity":166.274,"release_date":"2026-06-24","softcore":false,"video":false,"vote_average":6.39,"vote_count":136},{"adult":false,"backdrop_path":"/xLdw1xdHocKYFFvx7w41NchXMfJ.jpg","id":124364,"name":"FROM","original_name":"FROM","overview":"Unravel the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normalcy and search for a way out, they must also survive the threats of the surrounding forest – including the terrifying creatures that come out when the sun goes down.","poster_path":"/pRtJagIxpfODzzb0T0NAvZSzErC.jpg","media_type":"tv","original_language":"en","genre_ids":[9648,18,10765],"popularity":394.3642,"first_air_date":"2022-02-20","softcore":false,"vote_average":8.504,"vote_count":3950,"origin_country":["US"]},{"adult":false,"backdrop_path":"/qjTqY5coNiz6sVtPng40IzltsoN.jpg","id":1084244,"title":"Toy Story 5","original_title":"Toy Story 5","overview":"When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.","poster_path":"/sfQtVlIHljToOwYjhe21KPGzZWK.jpg","media_type":"movie","original_language":"en","genre_ids":[16,10751,35,12],"popularity":658.6359,"release_date":"2026-06-17","softcore":false,"video":false,"vote_average":7.4,"vote_count":538},{"adult":false,"backdrop_path":"/jIyEmnBrZtl6SEWyBoMO2hZnzMa.jpg","id":138502,"name":"X-Men '97","original_name":"X-Men '97","overview":"The X-Men, a band of mutants who use their uncanny gifts to protect a world that hates and fears them, are challenged like never before, forced to face a dangerous and unexpected new future.","poster_path":"/2HKBc5UiFw8JrruHq8S1Y7TnlW0.jpg","media_type":"tv","original_language":"en","genre_ids":[16,10759,10765],"popularity":92.5919,"first_air_date":"2024-03-20","softcore":false,"vote_average":8.589,"vote_count":738,"origin_country":["US"]},{"adult":false,"backdrop_path":"/kLA1GqiOEyVgXxgNqLoCr7bYcqu.jpg","id":950028,"title":"The Invite","original_title":"The Invite","overview":"Joe and Angela's marriage is on thin ice. When they invite their enigmatic upstairs neighbors for a dinner party, the night spirals into unexpected places. Have they reignited the spark or lit the match that burns it all down?","poster_path":"/b7Dr8Chzse8VagexAporUu2RtLx.jpg","media_type":"movie","original_language":"en","genre_ids":[18,35],"popularity":21.8105,"release_date":"2026-06-25","softcore":false,"video":false,"vote_average":7.875,"vote_count":24},{"adult":false,"backdrop_path":"/4ei68OmZr0XHnN82OjiV8GBqfyN.jpg","id":312949,"name":"Chainsmoker Cat","original_name":"ヤニねこ","overview":"Catgirl Yani struggles to pay her rent and keep a job while feeding her smoking habit. As her loved ones' concerns grow, she must rethink her future.","poster_path":"/kqeKlSd7o9BCbTraZsDnksRSfxm.jpg","media_type":"tv","original_language":"ja","genre_ids":[16,35,10765],"popularity":472.8364,"first_air_date":"2026-07-03","softcore":false,"vote_average":8.6,"vote_count":11,"origin_country":["JP"]},{"adult":false,"backdrop_path":"/uTWhbLc7Bj4qNSdW3ZvZKL8cOHv.jpg","id":125988,"name":"Silo","original_name":"Silo","overview":"In a ruined and toxic future, thousands live in a giant silo deep underground. After its sheriff breaks a cardinal rule and residents die mysteriously, engineer Juliette starts to uncover shocking secrets and the truth about the silo.","poster_path":"/gMYZZvnkVNTqSVnVCphWbPXwWwb.jpg","media_type":"tv","original_language":"en","genre_ids":[10765,18],"popularity":226.2373,"first_air_date":"2023-05-04","softcore":false,"vote_average":8.2,"vote_count":2197,"origin_country":["US"]},{"adult":false,"backdrop_path":"/t6O6XWelu27BD0OmIDCCufZZT6d.jpg","id":1301421,"title":"The Sheep Detectives","original_title":"The Sheep Detectives","overview":"George Hardy is a shepherd who reads detective novels to his beloved sheep every night, assuming they can't possibly understand. But when a mysterious incident disrupts life on the farm, the sheep realize they must become the detectives. As they follow the clues and investigate human suspects, they prove that even sheep can be brilliant crime-solvers.","poster_path":"/TEaSqmI6TZQVimULYbingDIdXT.jpg","media_type":"movie","original_language":"en","genre_ids":[12,35,80,10751,9648],"popularity":118.7959,"release_date":"2026-04-30","softcore":false,"video":false,"vote_average":7.827,"vote_count":799}],"total_pages":500,"total_results":10000}

In [ ]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/fBieUo3SdItUrXZE16YxbpjwXIe.jpg',
   'id': 283304,
   'name': 'Little House on the Prairie',
   'original_name': 'Little House on the Prairie',
   'overview': 'The close-knit Ingalls family builds a new life on the Western frontier, where the joys of nature and the struggle for survival are deeply intertwined.',
   'poster_path': '/oWUGSadxC9vQPOCeHDDVfDezmQC.jpg',
   'media_type': 'tv',
   'original_language': 'en',
   'genre_ids': [18, 37, 10751],
   'popularity': 41.8913,
   'first_air_date': '2026-07-09',
   'softcore': False,
   'vote_average': 5.833,
   'vote_count': 6,
   'origin_country': ['US']},
  {'adult': False,
   'backdrop_path': '/A5Tz6ogGt4VV8NESG9oWVct5bo1.jpg',
   'id': 1212763,
   'title': 'Evil Dead Burn',
   'original_title': 'Evil Dead Burn',
   'overview': 'After the loss of her husband, a woman seeks solace with her in-laws. As one by one they transform into deadites, she comes to discover that the vows she took in life - survive even in death.',
   'poster_path': '/ztadKzIIR0ERYqpHteaPFtk7inP.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27, 53],
   'popularity': 58.8586,
   'release_date': '2026-07-07',
   'softcore': False,
   'video': False,
   'vote_average': 7.3,
   'vote_count': 25},
  {'adult': False,
   'backdrop_path': '/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg',
   'id': 1339713,
   'title': 'Obsession',
   'original_title': 'Obsession',
   'overview': 'After breaking the mysterious "One Wish Willow" to win his crush\'s heart, a hopeless romantic finds himself getting exactly what he asked for but soon discovers that some desires come at a dark, sinister price.',
   'poster_path': '/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27, 53],
   'popularity': 722.1192,
   'release_date': '2026-05-13',
   'softcore': False,
   'video': False,
   'vote_average': 8.274,
   'vote_count': 2455},
  {'adult': False,
   'backdrop_path': '/1AVF2fAevpfi2HP6AEpptG1kg8R.jpg',
   'id': 1280738,
   'title': 'The Furious',
   'original_title': '火遮眼',
   'overview': "After Wang Wei's daughter is kidnapped by a criminal network and he receives no help from the corrupt police, Wei sets out to find her himself. His only ally is Navin, a relentless journalist whose wife has mysteriously disappeared. Fueled by a furious vengeance, the unlikely duo ruthlessly battle the kidnappers in this explosive martial arts showdown.",
   'poster_path': '/zP19YO60jwEsfKd5Qf1UvA5uJu8.jpg',
   'media_type': 'movie',
   'original_language': 'zh',
   'genre_ids': [28, 80, 53],
   'popularity': 275.0029,
   'release_date': '2026-06-10',
   'softcore': False,
   'video': False,
   'vote_average': 7.6,
   'vote_count': 119},
  {'adult': False,
   'backdrop_path': '/m3Pom6pbD51bBv3syz8NMHda3fz.jpg',
   'id': 1368337,
   'title': 'The Odyssey',
   'original_title': 'The Odyssey',
   'overview': 'Odysseus, the legendary King of Ithaca, embarks on a long and perilous journey home following the Trojan War. Throughout his voyage, he is forced to confront the whims of gods, mythological monsters, and trials that stretch both his cunning and his humanity to the breaking point.',
   'poster_path': '/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [12, 28, 14],
   'popularity': 95.9651,
   'release_date': '2026-07-15',
   'softcore': False,
   'video': False,
   'vote_average': 5.5,
   'vote_count': 4},
  {'adult': False,
   'backdrop_path': '/mCpwRayjXMFzKHbjbzc5JRKfq1O.jpg',
   'id': 1083381,
   'title': 'Backrooms',
   'original_title': 'Backrooms',
   'overview': 'A strange doorway appears in the basement of a furniture showroom.',
   'poster_path': '/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27, 9648, 878],
   'popularity': 466.6709,
   'release_date': '2026-05-27',
   'softcore': False,
   'video': False,
   'vote_average': 6.82,
   'vote_count': 959},
  {'adult': False,
   'backdrop_path': '/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg',
   'id': 1108427,
   'title': 'Moana',
   'original_title': 'Moana',
   'overview': "Moana answers the Ocean's call and, for the first time, voyages beyond the reef of her island of Motunui with the infamous demigod Maui on an unforgettable journey to restore prosperity to her people.",
   'poster_path': '/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [10751, 14, 35, 12],
   'popularity': 98.5184,
   'release_date': '2026-07-08',
   'softcore': False,
   'video': False,
   'vote_average': 4.758,
   'vote_count': 33},
  {'adult': False,
   'backdrop_path': '/wK1SL5EUJ6Bq2UhDCRtT1FA1HdN.jpg',
   'id': 297826,
   'name': 'Tomb Raider King',
   'original_name': '도굴왕',
   'overview': 'Chaos ensues overnight when mysterious tombs suddenly surface, filled with divine relics granting overwhelming power, triggering a global power struggle to claim them for dominion. Among the havoc, a raider, Jooheon Suh, is betrayed and left for dead until a second chance brings him back years before the relics. Fueled by fury and future knowledge, he sets out to raid each tomb before they arise.',
   'poster_path': '/xDW6cor12UD0b2IqboQWnrIn0UO.jpg',
   'media_type': 'tv',
   'original_language': 'ko',
   'genre_ids': [16, 10759, 10765],
   'popularity': 25.8928,
   'first_air_date': '2026-07-09',
   'softcore': False,
   'vote_average': 0.0,
   'vote_count': 0,
   'origin_country': ['KR']},
  {'adult': False,
   'backdrop_path': '/3pDfu71mrzSuFYyIfnKEjt8z4BC.jpg',
   'id': 1368314,
   'title': 'Passenger',
   'original_title': 'Passenger',
   'overview': "After a young couple witnesses a gruesome highway accident, they soon realize they did not leave the crash scene alone, as a demonic presence called the Passenger that won't stop until it claims them both turns their van life adventure into a nightmare.",
   'poster_path': '/2sOEJzhPzjTkZSlPbGxOJ7xgIyS.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [27, 53],
   'popularity': 184.6921,
   'release_date': '2026-05-20',
   'softcore': False,
   'video': False,
   'vote_average': 5.8,
   'vote_count': 149},
  {'adult': False,
   'backdrop_path': '/i5E9H7Ik0u61ylDDTbmUpTL3Yw.jpg',
   'id': 1170608,
   'title': 'Dune: Part Three',
   'original_title': 'Dune: Part Three',
   'overview': 'As Emperor, Paul Atreides grapples with the consequences of his rise to power as political conspiracies and a galaxy-spanning holy war threaten the future he alone can foresee.',
   'poster_path': '/d43fvHQsIMa4kpyhKXw0haEJIvI.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [28, 12, 878],
   'popularity': 18.7772,
   'release_date': '2026-12-16',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/feISh3qoREwIPWbSaLqqumbmh7m.jpg',
   'id': 322055,
   'name': "The Prosecutor's Proposal",
   'original_name': '검사실의 제안',
   'overview': "A victim’s son and a killer’s son reunite as a prosecutor and investigator, fighting systemic corruption while becoming each other's salvation.",
   'poster_path': '/lK6DrnFecG0AsA8O5UqEYOrOArd.jpg',
   'media_type': 'tv',
   'original_language': 'ko',
   'genre_ids': [9648, 80, 18],
   'popularity': 244.8945,
   'first_air_date': '2026-06-25',
   'softcore': False,
   'vote_average': 5.0,
   'vote_count': 4,
   'origin_country': ['KR']},
  {'adult': False,
   'backdrop_path': '/6tByIjKn3VLEVHhfpiNNWrnSIOM.jpg',
   'id': 1710008,
   'title': 'Nothing to Lose',
   'original_title': "Jusqu'au bout",
   'overview': 'She gave everything to become a mother, so when her young son falls ill, Jada will stop at  nothing to find a donor and save him — no matter the cost.',
   'poster_path': '/3SKN8QZptMm8KfCCQtEmyh1Zkgz.jpg',
   'media_type': 'movie',
   'original_language': 'fr',
   'genre_ids': [18, 28],
   'popularity': 28.5307,
   'release_date': '2026-07-08',
   'softcore': False,
   'video': False,
   'vote_average': 4.25,
   'vote_count': 12},
  {'adult': False,
   'backdrop_path': '/xMoXsOgF0hBP7iVj7ZPIrFtTeL3.jpg',
   'id': 1315772,
   'title': 'Minions & Monsters',
   'original_title': 'Minions & Monsters',
   'overview': 'This is the rambunctious, ridiculous and totally true story of how the Minions conquered Hollywood, became movie stars, lost everything, unleashed monsters onto the world and then banded together to try and save the planet from the mayhem they had just created.',
   'poster_path': '/nz7i42yhLIJ4ve9JKgM6NthoLHO.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [12, 16, 35, 10751, 14],
   'popularity': 166.274,
   'release_date': '2026-06-24',
   'softcore': False,
   'video': False,
   'vote_average': 6.39,
   'vote_count': 136},
  {'adult': False,
   'backdrop_path': '/xLdw1xdHocKYFFvx7w41NchXMfJ.jpg',
   'id': 124364,
   'name': 'FROM',
   'original_name': 'FROM',
   'overview': 'Unravel the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normalcy and search for a way out, they must also survive the threats of the surrounding forest – including the terrifying creatures that come out when the sun goes down.',
   'poster_path': '/pRtJagIxpfODzzb0T0NAvZSzErC.jpg',
   'media_type': 'tv',
   'original_language': 'en',
   'genre_ids': [9648, 18, 10765],
   'popularity': 394.3642,
   'first_air_date': '2022-02-20',
   'softcore': False,
   'vote_average': 8.504,
   'vote_count': 3950,
   'origin_country': ['US']},
  {'adult': False,
   'backdrop_path': '/qjTqY5coNiz6sVtPng40IzltsoN.jpg',
   'id': 1084244,
   'title': 'Toy Story 5',
   'original_title': 'Toy Story 5',
   'overview': "When Bonnie receives a Lilypad tablet as a gift and becomes obsessed, Buzz, Woody, Jessie and the rest of the gang's jobs become exponentially harder when they have to go head to head with the all-new threat to playtime.",
   'poster_path': '/sfQtVlIHljToOwYjhe21KPGzZWK.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [16, 10751, 35, 12],
   'popularity': 658.6359,
   'release_date': '2026-06-17',
   'softcore': False,
   'video': False,
   'vote_average': 7.4,
   'vote_count': 538},
  {'adult': False,
   'backdrop_path': '/jIyEmnBrZtl6SEWyBoMO2hZnzMa.jpg',
   'id': 138502,
   'name': "X-Men '97",
   'original_name': "X-Men '97",
   'overview': 'The X-Men, a band of mutants who use their uncanny gifts to protect a world that hates and fears them, are challenged like never before, forced to face a dangerous and unexpected new future.',
   'poster_path': '/2HKBc5UiFw8JrruHq8S1Y7TnlW0.jpg',
   'media_type': 'tv',
   'original_language': 'en',
   'genre_ids': [16, 10759, 10765],
   'popularity': 92.5919,
   'first_air_date': '2024-03-20',
   'softcore': False,
   'vote_average': 8.589,
   'vote_count': 738,
   'origin_country': ['US']},
  {'adult': False,
   'backdrop_path': '/kLA1GqiOEyVgXxgNqLoCr7bYcqu.jpg',
   'id': 950028,
   'title': 'The Invite',
   'original_title': 'The Invite',
   'overview': "Joe and Angela's marriage is on thin ice. When they invite their enigmatic upstairs neighbors for a dinner party, the night spirals into unexpected places. Have they reignited the spark or lit the match that burns it all down?",
   'poster_path': '/b7Dr8Chzse8VagexAporUu2RtLx.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [18, 35],
   'popularity': 21.8105,
   'release_date': '2026-06-25',
   'softcore': False,
   'video': False,
   'vote_average': 7.875,
   'vote_count': 24},
  {'adult': False,
   'backdrop_path': '/4ei68OmZr0XHnN82OjiV8GBqfyN.jpg',
   'id': 312949,
   'name': 'Chainsmoker Cat',
   'original_name': 'ヤニねこ',
   'overview': "Catgirl Yani struggles to pay her rent and keep a job while feeding her smoking habit. As her loved ones' concerns grow, she must rethink her future.",
   'poster_path': '/kqeKlSd7o9BCbTraZsDnksRSfxm.jpg',
   'media_type': 'tv',
   'original_language': 'ja',
   'genre_ids': [16, 35, 10765],
   'popularity': 472.8364,
   'first_air_date': '2026-07-03',
   'softcore': False,
   'vote_average': 8.6,
   'vote_count': 11,
   'origin_country': ['JP']},
  {'adult': False,
   'backdrop_path': '/uTWhbLc7Bj4qNSdW3ZvZKL8cOHv.jpg',
   'id': 125988,
   'name': 'Silo',
   'original_name': 'Silo',
   'overview': 'In a ruined and toxic future, thousands live in a giant silo deep underground. After its sheriff breaks a cardinal rule and residents die mysteriously, engineer Juliette starts to uncover shocking secrets and the truth about the silo.',
   'poster_path': '/gMYZZvnkVNTqSVnVCphWbPXwWwb.jpg',
   'media_type': 'tv',
   'original_language': 'en',
   'genre_ids': [10765, 18],
   'popularity': 226.2373,
   'first_air_date': '2023-05-04',
   'softcore': False,
   'vote_average': 8.2,
   'vote_count': 2197,
   'origin_country': ['US']},
  {'adult': False,
   'backdrop_path': '/t6O6XWelu27BD0OmIDCCufZZT6d.jpg',
   'id': 1301421,
   'title': 'The Sheep Detectives',
   'original_title': 'The Sheep Detectives',
   'overview': "George Hardy is a shepherd who reads detective novels to his beloved sheep every night, assuming they can't possibly understand. But when a mysterious incident disrupts life on the farm, the sheep realize they must become the detectives. As they follow the clues and investigate human suspects, they prove that even sheep can be brilliant crime-solvers.",
   'poster_path': '/TEaSqmI6TZQVimULYbingDIdXT.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [12, 35, 80, 10751, 9648],
   'popularity': 118.7959,
   'release_date': '2026-04-30',
   'softcore': False,
   'video': False,
   'vote_average': 7.827,
   'vote_count': 799}],
 'total_pages': 500,
 'total_results': 10000}

In [ ]:
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,id,name,original_name,overview,poster_path,media_type,original_language,genre_ids,popularity,first_air_date,softcore,vote_average,vote_count,origin_country,title,original_title,release_date,video
0,False,/fBieUo3SdItUrXZE16YxbpjwXIe.jpg,283304,Little House on the Prairie,Little House on the Prairie,The close-knit Ingalls family builds a new lif...,/oWUGSadxC9vQPOCeHDDVfDezmQC.jpg,tv,en,"[18, 37, 10751]",41.8913,2026-07-09,False,5.833,6,[US],NaN,NaN,NaN,NaN
1,False,/A5Tz6ogGt4VV8NESG9oWVct5bo1.jpg,1212763,NaN,NaN,"After the loss of her husband, a woman seeks s...",/ztadKzIIR0ERYqpHteaPFtk7inP.jpg,movie,en,"[27, 53]",58.8586,NaN,False,7.300,25,NaN,Evil Dead Burn,Evil Dead Burn,2026-07-07,False
2,False,/rZfmzpixLKLR3Hg2u0WgC7XLFl8.jpg,1339713,NaN,NaN,"After breaking the mysterious ""One Wish Willow...",/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg,movie,en,"[27, 53]",722.1192,NaN,False,8.274,2455,NaN,Obsession,Obsession,2026-05-13,False
3,False,/1AVF2fAevpfi2HP6AEpptG1kg8R.jpg,1280738,NaN,NaN,After Wang Wei's daughter is kidnapped by a cr...,/zP19YO60jwEsfKd5Qf1UvA5uJu8.jpg,movie,zh,"[28, 80, 53]",275.0029,NaN,False,7.600,119,NaN,The Furious,火遮眼,2026-06-10,False
4,False,/m3Pom6pbD51bBv3syz8NMHda3fz.jpg,1368337,NaN,NaN,"Odysseus, the legendary King of Ithaca, embark...",/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,movie,en,"[12, 28, 14]",95.9651,NaN,False,5.500,4,NaN,The Odyssey,The Odyssey,2026-07-15,False
5,False,/mCpwRayjXMFzKHbjbzc5JRKfq1O.jpg,1083381,NaN,NaN,A strange doorway appears in the basement of a...,/rhGx6E3qRNMgj3i5su2oukNHwIQ.jpg,movie,en,"[27, 9648, 878]",466.6709,NaN,False,6.820,959,NaN,Backrooms,Backrooms,2026-05-27,False
6,False,/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg,1108427,NaN,NaN,"Moana answers the Ocean's call and, for the fi...",/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg,movie,en,"[10751, 14, 35, 12]",98.5184,NaN,False,4.758,33,NaN,Moana,Moana,2026-07-08,False
7,False,/wK1SL5EUJ6Bq2UhDCRtT1FA1HdN.jpg,297826,Tomb Raider King,도굴왕,Chaos ensues overnight when mysterious tombs s...,/xDW6cor12UD0b2IqboQWnrIn0UO.jpg,tv,ko,"[16, 10759, 10765]",25.8928,2026-07-09,False,0.000,0,[KR],NaN,NaN,NaN,NaN
8,False,/3pDfu71mrzSuFYyIfnKEjt8z4BC.jpg,1368314,NaN,NaN,After a young couple witnesses a gruesome high...,/2sOEJzhPzjTkZSlPbGxOJ7xgIyS.jpg,movie,en,"[27, 53]",184.6921,NaN,False,5.800,149,NaN,Passenger,Passenger,2026-05-20,False
9,False,/i5E9H7Ik0u61ylDDTbmUpTL3Yw.jpg,1170608,NaN,NaN,"As Emperor, Paul Atreides grapples with the co...",/d43fvHQsIMa4kpyhKXw0haEJIvI.jpg,movie,en,"[28, 12, 878]",18.7772,NaN,False,0.000,0,NaN,Dune: Part Three,Dune: Part Three,2026-12-16,False
10,False,/feISh3qoREwIPWbSaLqqumbmh7m.jpg,322055,The Prosecutor's Proposal,검사실의 제안,A victim’s son and a killer’s son reunite as a...,/lK6DrnFecG0AsA8O5UqEYOrOArd.jpg,tv,ko,"[9648, 80, 18]",244.8945,2026-06-25,False,5.000,4,[KR],NaN,NaN,NaN,NaN
11,False,/6tByIjKn3VLEVHhfpiNNWrnSIOM.jpg,1710008,NaN,NaN,"She gave everything to become a mother, so whe...",/3SKN8QZptMm8KfCCQtEmyh1Zkgz.jpg,movie,fr,"[18, 28]",28.5307,NaN,False,4.250,12,NaN,Nothing to Lose,Jusqu'au bout,2026-07-08,False
12,False,/xMoXsOgF0hBP7iVj7ZPIrFtTeL3.jpg,1315772,NaN,NaN,"This is the rambunctious, ridiculous and total...",/nz7i42yhLIJ4ve9JKgM6NthoLHO.jpg,movie,en,"[12, 16, 35, 10751, 14]",166.2740,NaN,False,6.390,136,NaN,Minions & Monsters,Minions & Monsters,2026-06-24,False
13,False,/xLdw1xdHocKYFFvx7w41NchXMfJ.jpg,124364,FROM,FROM,Unravel the mystery of a nightmarish town in m...,/pRtJagIxpfODzzb0T0NAvZSzErC.jpg,tv,en,"[9648, 18, 10765]",394.3642,2022-02-20,False,8.504,3950,[US],NaN,NaN,NaN,NaN
14,False,/qjTqY5coNiz6sVtPng40IzltsoN.jpg,1084244,NaN,NaN,When Bonnie receives a Lilypad tablet as a gif...,/sfQtVlIHljToOwYjhe21KPGzZWK.jpg,movie,en,"[16, 10751, 35, 12]",658.6359,NaN,False,7.400,538,NaN,Toy Story 5,Toy Story 5,2026-06-17,False
15,False,/jIyEmnBrZtl6SEWyBoMO2hZnzMa.jpg,138502,X-Men '97,X-Men '97,"The X-Men, a band of mutants who use their unc...",/2HKBc5UiFw8JrruHq8S1Y7TnlW0.jpg,tv,en,"[16, 10759, 10765]",92.5919,2024-03-20,False,8.589,738,[US],NaN,NaN,NaN,NaN
16,False,/kLA1GqiOEyVgXxgNqLoCr7bYcqu.jpg,950028,NaN,NaN,Joe and Angela's marriage is on thin ice. When...,/b7Dr8Chzse8VagexAporUu2RtLx.jpg,movie,en,"[18, 35]",21.8105,NaN,False,7.875,24,NaN,The Invite,The Invite,2026-06-25,False
17,False,/4ei68OmZr0XHnN82OjiV8GBqfyN.jpg,312949,Chainsmoker Cat,ヤニねこ,Catgirl Yani struggles to pay her rent and kee...,/kqeKlSd7o9BCbTraZsDnksRSfxm.jpg,tv,ja,"[16, 35, 10765]",472.8364,2026-07-03,False,8.600,11,[JP],NaN,NaN,NaN,NaN
18,False,/uTWhbLc7Bj4qNSdW3ZvZKL8cOHv.jpg,125988,Silo,Silo,"In a ruined and toxic future, thousands live i...",/gMYZZvnkVNTqSVnVCphWbPXwWwb.jpg,tv,en,"[10765, 18]",226.2373,2023-05-04,False,8.200,2197,[US],NaN,NaN,NaN,NaN
19,False,/t6O6XWelu27BD0OmIDCCufZZT6d.jpg,1301421,NaN,NaN,George Hardy is a shepherd who reads detective...,/TEaSqmI6TZQVimULYbingDIdXT.jpg,movie,en,"[12, 35, 80, 10751, 9648]",118.7959,NaN,False,7.827,799,NaN,The Sheep Detectives,The Sheep Detectives,2026-04-30,False

In [33]:
import http.client
import json

conn = http.client.HTTPSConnection("imdb-top-100-movies.p.rapidapi.com")

headers = {
    'x-rapidapi-key': "4208a964f5mshb78c8bc390f8defp13cb64jsn57d0b96d25f4",
    'x-rapidapi-host': "imdb-top-100-movies.p.rapidapi.com",
    'Content-Type': "application/json"
}

conn.request("GET", "/", headers=headers)

res = conn.getresponse()
data = res.read()

json_strings=data.decode("utf-8")

movie_list=json.loads(json_strings)

df = pd.DataFrame(movie_list)
df

,rank,title,description,image,big_image,genre,thumbnail,rating,id,year,imdbid,imdb_link
0,1,The Shawshank Redemption,Two imprisoned men bond over a number of years...,https://m.media-amazon.com/images/M/MV5BMDFkYT...,https://m.media-amazon.com/images/M/MV5BMDFkYT...,[Drama],https://m.media-amazon.com/images/M/MV5BMDFkYT...,9.3,top1,1994,tt0111161,https://www.imdb.com/title/tt0111161
1,2,The Godfather,The aging patriarch of an organized crime dyna...,https://m.media-amazon.com/images/M/MV5BM2MyNj...,https://m.media-amazon.com/images/M/MV5BM2MyNj...,"[Crime, Drama]",https://m.media-amazon.com/images/M/MV5BM2MyNj...,9.2,top2,1972,tt0068646,https://www.imdb.com/title/tt0068646
2,3,The Dark Knight,When the menace known as the Joker wreaks havo...,https://m.media-amazon.com/images/M/MV5BMTMxNT...,https://m.media-amazon.com/images/M/MV5BMTMxNT...,"[Action, Crime, Drama]",https://m.media-amazon.com/images/M/MV5BMTMxNT...,9.0,top3,2008,tt0468569,https://www.imdb.com/title/tt0468569
3,4,The Godfather Part II,The early life and career of Vito Corleone in ...,https://m.media-amazon.com/images/M/MV5BMWMwMG...,https://m.media-amazon.com/images/M/MV5BMWMwMG...,"[Crime, Drama]",https://m.media-amazon.com/images/M/MV5BMWMwMG...,9.0,top4,1974,tt0071562,https://www.imdb.com/title/tt0071562
4,5,12 Angry Men,The jury in a New York City murder trial is fr...,https://m.media-amazon.com/images/M/MV5BMWU4N2...,https://m.media-amazon.com/images/M/MV5BMWU4N2...,"[Crime, Drama]",https://m.media-amazon.com/images/M/MV5BMWU4N2...,9.0,top5,1957,tt0050083,https://www.imdb.com/title/tt0050083
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Reservoir Dogs,When a simple jewelry heist goes horribly wron...,https://m.media-amazon.com/images/M/MV5BZmExNm...,https://m.media-amazon.com/images/M/MV5BZmExNm...,"[Crime, Thriller]",https://m.media-amazon.com/images/M/MV5BZmExNm...,8.3,top96,1992,tt0105236,https://www.imdb.com/title/tt0105236
96,97,Ikiru,A bureaucrat tries to find meaning in his life...,https://m.media-amazon.com/images/M/MV5BYWM1Ym...,https://m.media-amazon.com/images/M/MV5BYWM1Ym...,[Drama],https://m.media-amazon.com/images/M/MV5BYWM1Ym...,8.3,top97,1952,tt0044741,https://www.imdb.com/title/tt0044741
97,98,Lawrence of Arabia,"The story of T.E. Lawrence, the English office...",https://m.media-amazon.com/images/M/MV5BYWY5Zj...,https://m.media-amazon.com/images/M/MV5BYWY5Zj...,"[Adventure, Biography, Drama]",https://m.media-amazon.com/images/M/MV5BYWY5Zj...,8.3,top98,1962,tt0056172,https://www.imdb.com/title/tt0056172
98,99,Citizen Kane,Following the death of publishing tycoon Charl...,https://m.media-amazon.com/images/M/MV5BYjBiOT...,https://m.media-amazon.com/images/M/MV5BYjBiOT...,"[Drama, Mystery]",https://m.media-amazon.com/images/M/MV5BYjBiOT...,8.3,top99,1941,tt0033467,https://www.imdb.com/title/tt0033467
99,100,M,When the police in a German city are unable to...,https://m.media-amazon.com/images/M/MV5BODA4OD...,https://m.media-amazon.com/images/M/MV5BODA4OD...,"[Crime, Mystery, Thriller]",https://m.media-amazon.com/images/M/MV5BODA4OD...,8.3,top100,1931,tt0022100,https://www.imdb.com/title/tt0022100

In [34]:
df.to_csv('mov_list.csv',index=False)